### ISSUE TITLE
Print to PDF  (FPA v1.6.0)

### ISSUE THREAD

**Issue by AMurray2016** [ForumPostAssistant/FPA#104]
Hi
I love the improvements to the FPA, great work.

One issue I found is the "print to pdf" appears not to be working. 

On clicking the link I see a thin progress bar across the top of the screen, but no further response, and no file in my 'downloads' folder nor any prompt to open or save the file.

Using Firefox 77.0.1 (Win 10, 64-bit)

Thanks.

**Comment by sozzled** [comment]
G'day, Andy, and thanks.

I haven't tried using the print to PDF feature with Firefox on Win 10 (yet); I've tested using Win 8.1 (and Firefox) and it works there.  I'll give it a go in a minute.

UPDATE:  I tried it from a Win 10 (64-bit FF 77.0.1 browser) and can confirm, from my end, everything appears to work.  You're right that a progress bar appears across the top of the screen and it seems to take several seconds before the progress bar reaches the end before the option to download the PDF file is displayed.  I can't say what may be the issue in your case.

**Comment by RussW** [comment]
Just checked with the html2canvas library developer and this issue with Firefox has just been reported to them as well (2 days ago), so at this moment in time we will have to wait for an update from them at some point, but as far as my testing has gone, this appears to be the only browsers effected.

- PHP 6.5 is the minimum supported PHP version, for both th html2canvas and PDF generation libraries.

- This canvas generation and the subsequent pdf generation run as separate processes, so each receive the maximum PHP runtime memory & execution time configured on the server.

- At the moment the the html2canvas .jpg quality is set to **_95%_**, which can generate larger file sizes, we can look in to reducing the canvas quality at a later date if required.

- The Print2PDF function has been requested many times, and as such is not a "_gimmick_" but a feature request that has been fulfilled and hopefully is useful for those that do not purely use FPA for forum posts.

**Comment by sozzled** [comment]
I don't want to argue.  While the print-to-PDF feature may have been requested it could be useful.  I didn't mean to imply that it's a gimmick as a way of downplaying its potential value.  Some people may find it useful and that's a good thing.  I haven't tried to run this feature on less than PHP 7 and so, if it doesn't work in that environment, that's just something we have to accept as a limitation.

**Comment by sozzled** [comment]
Thanks, Andy.  I've tested the print-to-PDF feature with Firefox 77.0.1 on Win 8.1 and 10 (with one test website running PHP 7.3.something) and the feature works for me.  The feature appears to work for those of us who have used it; that's not to say that it doesn't work all the time and that we don't know all the issues involved with the html2pdf function that @RussW used. Cheers, mate. :)

**Comment by AMurray2016** [comment]
Thanks all.  If I ever needed it I can just use print to PDF that I have in my PC anyway (I have adobe pro, and it installs a PDF "printer".  Again, great work on the FPA itself.
