### ISSUE TITLE
PHP Fatal Error on Joomla Live Check

### ISSUE THREAD

**Issue by RussW** [ForumPostAssistant/FPA#105]
FPA receives a PHP Fatal Error when checking for the latest Joomla! release if "allow_url_fopen" is disabled.

Check for php _allow_url_fopen_ enabled before running the doJOOMLALIVE function

**Comment by sozzled** [comment]
Very good.  I was going to suggest that we do something to highlight the state of allow_url_fopen() in the FPA report (both GUI and FPA) because this setting impacts the ability to use the Joomla! Update component.  We know that there certain PHP settings (e.g. Max. POST size and Max. Upload Size) which, improperly or inadequately set, affect a website owner's ability to install extensions as well as update J!.

It may be an idea to use a "traffic light" system to indicate these settings (and possibly "score" things in the confidence measure)?

**Comment by RussW** [comment]
have added _"allow_url_fopen"_ to the "Confidence Rating" as well ( https://github.com/ForumPostAssistant/FPA/commit/8f42c078272793beb745a4983b74fe4c53fd01d9 )

**Comment by frostmakk** [comment]
Would it be nice to put in an else statement around line 4180 with a different colored box saying something like "Could not be tested", instead of the box just missing?

**Comment by RussW** [comment]
absolutely, just a simple info box stating remote urls disabled or simplexml not available unable to check etc...  would certainly be more user-friendly than just not showing anything.

Do you have time? or want me to have a tinker?

**Comment by frostmakk** [comment]
Since I'm not a native English speaking person, my sentences are never short enough to fit into a small box.  😢

**Comment by RussW** [comment]
You do well enough young sir (plus, your english is far better than my 20 year old Norwegian), just updated to commit ( https://github.com/ForumPostAssistant/FPA/commit/23ee11196fe9fb18e280cca3808d1b862f41d308 ) now with a message if SimpleXML or allow_url_fopen not available.

If you are happy and wish to PR/Release, go for it, unless we wait a few more days to see if any other reports come in.

**Comment by frostmakk** [comment]
Just thinking...
If $canDOLIVE is false, both boxes will be missing.
Is this visually ok, or would you like to do something about that as well?

**Comment by RussW** [comment]
I was happy to just not show anything if canDOLIVE is false, the viewer knows no different at that point, so I didn't think we needed to tell them that we couldn't do something, **but** if you think we need to inform the user of the fact that we couldn't perform those tasks, go for it, I have no problem.

_[edit]_ the confidence rating will be reduced if cURL and allow_url_fopen or not available and will be noted in the dropdown list.

**Comment by frostmakk** [comment]
It's ok for me. Just had to ask.
I will issue a bug fix release later today.

**Comment by RussW** [comment]
@frostmakk thank you, much appreciated as always.

**Comment by frostmakk** [comment]
Issue fixed. New release issued.
Closing.
