### ISSUE TITLE
FPA still finds uninstalled templates

### ISSUE THREAD

**Issue by mandville** [ForumPostAssistant/FPA#107]
https://forum.joomla.org/viewtopic.php?f=713&t=981747#p3612620

"
I ran FPa and saw that it reported some uninstalled templates, components, ....
How can I get rid of those "ghost lines" ? Is there a DB scrub that I'm supposed to run ?"

**Comment by frostmakk** [comment]
They are not in the database. The question mark behind some of the templates indicate that they were not found in the extensions table. The FPA list them because the extensions manifest file was found in the folder structure.

**Comment by RussW** [comment]
Correct me if I am wrong, but it appears from the forum post that the templates issue is now resolved to the OP removing remnants of older templates and hasn't updated for quite some time. Closing.
