### ISSUE TITLE
FPA v1.6.1 error 500 from mysqli_connect_errno()

### ISSUE THREAD

**Issue by toivo** [ForumPostAssistant/FPA#109]
FPA v1.6.1 fails in PHP 8.0 with HTTP 500 error because two calls to the function mysqli_connect_errno() in line 2365 have arguments.

Ref.  [https://forum.joomla.org/viewtopic.php?f=806&t=983306](url)

**Comment by frostmakk** [comment]
PR created. Please test.

**Comment by frostmakk** [comment]
FPA v1.6.2 released.

**Comment by RussW** [comment]
Thanks @frostmakk, appreciate your time and effort
