### ISSUE TITLE
Fatal error: Uncaught Exception when the timezone is 'America/New York'

### ISSUE THREAD

**Issue by toivo** [ForumPostAssistant/FPA#111]
FPA v1.6.2 reports an Uncaught Exception when the timezone is 'America/New York', reported in the forum topic  https://forum.joomla.org/viewtopic.php?f=710&t=985083#p3625595

`Fatal error: Uncaught Exception: DateTime::__construct(): Invalid date.timezone value 'America/New York', we selected the timezone 'UTC' for now. in /home/vetspetsandlaugh/public_html/fpa-en.php:189 Stack trace: #0 /home/vetspetsandlaugh/public_html/fpa-en.php(189): DateTime->__construct('01-03-2021') #1 {main} thrown in /home/vetspetsandlaugh/public_html/fpa-en.php on line 189`

**Comment by wojsmol** [comment]
@toivo This is coused by wrong php configuration on the server. Instead of `America/New York` time zone should be set to `America/New_York` with underscore - ref https://www.php.net/manual/en/timezones.america.php.

**Comment by toivo** [comment]
@wojsmol Thank you, I will forward the information to the member of the forum who reported the message and then close this issue.

**Comment by toivo** [comment]
Info added to the forum topic.
