### ISSUE TITLE
read my email?!!!

### ISSUE THREAD

**Issue by Haleymiranda79** [ForumPostAssistant/FPA#112]
Why does Github need to read my email act on my behalf for me to get help on the forums? Is that really a thing or am I hacked?

**Comment by AMurray2016** [comment]
I don't understand the question.....are you referring to using the FPA to post the system/joomla information into a post on the Joomla forum? (that is, https://forum.joomla.org)?

**Comment by Haleymiranda79** [comment]
Thank you so much for responding.  Github wants to act on my behalf and read my emails in order for me to download the forums and get help.  Sounded fishy so I'm reaching out. I know nothing  about github. I'm so sorry for posting in the wrong thread.

**Comment by sozzled** [comment]
I have no idea what we're talking about here.  "GitHub wants to act on my behalf and read my emails in order for me to download the forums" ???  Where did you read this?

I don't think your question relates to Joomla, the Joomla forum or the FPA project (just by looking at your GitHub profile).  I think you dialed the wrong number, sorry. ;)

**Comment by RussW** [comment]
based on profile research and OP other github interactions, possible spam account - closing
