### ISSUE TITLE
Framework Updates

### ISSUE THREAD

**Issue by RussW** [ForumPostAssistant/FPA#113]
**Test & Review Branch BS5.1-Update** ( https://github.com/ForumPostAssistant/FPA/tree/BS5.1-Update )
Please test when time allows...

**_Activity:_**
Update Bootstrap & Bootswatch to v5.1.0
Update FontAwesome to v5.15.4
Update Pace to v1.2.4
Remove jQuery & dependancies

**Comment by RussW** [comment]
PR ( https://github.com/ForumPostAssistant/FPA/pull/114 )

**Comment by frostmakk** [comment]
When this PR is merged, maybe we should consider doing PR's of the other branches that has been laying around for a while as well?
The loopProtection and PostgreSQL-User-Privileges.

**Comment by RussW** [comment]
I think you are right...
Seeing as it has been quite some time, I will try to find some time to re-test and re-confirm the LoopProtection fix before we proceed though, but I think your PostGres update should be good to go as it is though, if you agree?

If you are happy with #114 and have the time, would you like to prepare and release @frostmakk?

**Comment by frostmakk** [comment]
Merged #114 
Please test & merge PostgreSQL-User-Privileges #115 if satisfied.
If you don't want to include LoopProtection now, I'll make a new release when #115 is merged or rejected.

**Comment by frostmakk** [comment]
Included in v1.6.3
