### ISSUE TITLE
Upload-failure from joomla 3 to joomla 4

### ISSUE THREAD

**Issue by hoerbyhavn** [ForumPostAssistant/FPA#116]
Hi 
i have tried to upgrade from joomla 3 to joomla 4 in backend, both in "live-update" and in "upload and update".
No luck. 
check attached:
[joomla 4 fejler.pdf](https://github.com/ForumPostAssistant/FPA/files/7474233/joomla.4.fejler.pdf)
d

What to do?

regards Mogens

**Comment by frostmakk** [comment]
Follow the advices given to you in the Joomla! Forum.
https://forum.joomla.org/viewtopic.php?f=812&t=989747&p=3644347#p3644347
