### ISSUE TITLE
Failed to load 'g5_helium' template: mkdir(): Permission denied

### ISSUE THREAD

**Issue by p3core** [ForumPostAssistant/FPA#119]
Hello,

My Joomla website is http://nexia.live but I'm getting the below error...
--------------- Failed to load 'g5_helium' template: mkdir(): Permission denied
My Hosting is Windows Hosting...
My administrator section or http://nexia.live/administrator is working properly...
My website root is getting an error...
Can somebody please help me to resolve this error...
My Joomla Website version is 3.10.3...
I tried changing my Template to Beez3 or Protostar but I'm still getting the same error...
I'm also not able to change my site from offline to online...
**ERROR MESSAGE:-**
An error has occurred.
0 Could not write to the configuration file...
mkdir(): Permission denied
I think the issue is some permission error or something like that...
Anyway please do get back to me...

Thank you

Thank you in advance...

Regards,

Praveen Thomas

**Comment by RussW** [comment]
Thank you for contacting the FPA Team, we appreciate you making use of the FPA Utility, but we do not support Joomla! itself here, just the Forum Post Assistant utility.

If you haven't already, you can get Joomla! support from either the Joomla! Forum ( https://forum.joomla.org/ ) or if you prefer on the Joomla! Facebook Group ( https://www.facebook.com/groups/joomlanospam )

However, you are correct, your issue appears to be with the ownership or permissions of the "templates" directory, this is very likely to be a windows hosting issue, you may need to contact your host to confirm that your hosting account has the correct "write" permissions required.
