### ISSUE TITLE
Error: Unknown format specifier "n"

### ISSUE THREAD

**Issue by tecnico10** [ForumPostAssistant/FPA#121]
PHP: 8.1.5 and PHP: 8.0 error
PHP: 7.4 Ok
Template: Cassiopeia
Joomla: 4.1.4
Italian language
System Redirect: Unknown format specifier "n"

What's the problem?
![Immagine 2022-06-05 160655](https://user-images.githubusercontent.com/1893680/172054752-db565c1f-8f17-4a5b-812a-e2770223149c.jpg)

**Comment by sozzled** [comment]
Referenced at https://forum.joomla.org/viewtopic.php?f=808&t=994218.

Not a FPA issue; it's a problem caused by an error in the J! 4.1 Italian language pack.
