### ISSUE TITLE
The API folder is not listed under Folder Permissions

### ISSUE THREAD

**Issue by toivo** [ForumPostAssistant/FPA#122]
The FPA results mention the logs folder in the main Joomla folder, even if it does not exist.  Every Joomla 4 has the API folder and it would be good to list that among the folders in Core Folders Permissions Checks / Folder Permissions.

**Comment by sozzled** [comment]
Good idea.

**Comment by frostmakk** [comment]
Included in v1.6.6. release.

**Comment by toivo** [comment]
Thank you!
