### ISSUE TITLE
403 error code

### ISSUE THREAD

**Issue by silviudesign** [ForumPostAssistant/FPA#125]
Hello, 
after installing here: https://cursuri.silviusielenacovaliov.ro/oo/fpa-en.php the forum, when accesing it, 
It give a 403
Forbidden
Access to this resource on the server is denied!.
Thank you for any clue on this issue.

**Comment by RussW** [comment]
it sounds like you have a folder or file permissions or ownership problem, contact your host for further assistance, or open a discussion topic at https://forum.joomla.org/viewforum.php?f=806&sid=1e737f6d4e838ebca37c25d27935ebc1
