### ISSUE TITLE
Joomla website crash and lost access to backend

### ISSUE THREAD

**Issue by Wealtholaa** [ForumPostAssistant/FPA#130]
Hello community, i need help accessing my Joomla backend and website, i have done everything possible after trying to upgrade from joomla 3.10 to joomla 4 and my website crash.
Please I need urgent attention, I have tried to disable all the extensions on my hosting platform and tried other methods but this does not seem to work.
Please help me out.
https://detroitemnews.com/administrator/

**Comment by RussW** [comment]
This is not a Joomla support group.
Please try for support at https://forum.joomla.org or https://www.facebook.com/groups/joomlanospam
