### ISSUE TITLE
FPA 1.6.6 seems to be a little bit outdated

### ISSUE THREAD

**Issue by dautrich** [ForumPostAssistant/FPA#131]
I ran FPA 1.6.6 on one of my sites, which is perfectly working and updated to the latest releases of Joomla and PHP. 
But FPA obviously doesn't know J5.1.0 and rates my site with an "F":

![grafik](https://github.com/ForumPostAssistant/FPA/assets/7933215/0e382e71-a2ec-4925-8f5d-1cc77562074f)

**Comment by RussW** [comment]
Thanks Rolf, no FPA hasn't been fully updated for 5.1, it's on the list todo now.

**Comment by RussW** [comment]
This Commit/PR should add J5.0 compatibility and includes some J4 to J5 Pre~update environment checks as well. Displays a message on J4 if the environment does not reach J5 requirements. Would you be able to test please @dautrich?

https://github.com/ForumPostAssistant/FPA/blob/248af8a2aaa55ebf49022f420e895c6b2a427715/fpa-en.php

**Comment by dautrich** [comment]
In general, this looks good on a J5.1.0. I get a rating of A+, the "Additional Findings & Notes" are correct.
But there is still an error in the opening Environment Snapshot: J5.1 is supposed to be a development release, which is obviously wrong.

![grafik](https://github.com/ForumPostAssistant/FPA/assets/7933215/b7442dec-957e-47b8-87fb-b6ca8e973a29)


I'll try to check a J4.4 later.

**Comment by dautrich** [comment]
I successfully checked on a J4.4:

![grafik](https://github.com/ForumPostAssistant/FPA/assets/7933215/f7753812-db4b-4fad-9e9d-8ddb23c947b0)

The "Additional Findings & Notes" are correct as well.

**Comment by RussW** [comment]
thanks @dautrich 
the main branch id updated now to also resolve the "Development Status" error

https://github.com/ForumPostAssistant/FPA/archive/refs/heads/en-GB.zip

**Comment by dautrich** [comment]
I confirm that the  "Development Status" error has gone.

Are you going to release a new official version?

**Comment by RussW** [comment]
FPA v1.6.7 Released
https://github.com/ForumPostAssistant/FPA/releases/tag/v1.6.7

**Comment by RussW** [comment]
if you're happy with the release, I'll close this. Reopen it if you feel there is anything missing or still needs action.
