### ISSUE TITLE
FPA fails when it finds directories with 000 permissions.

### ISSUE THREAD

**Issue by PhilD13** [ForumPostAssistant/FPA#16]
Reported
When the FPA script is installed into a site that contains directories with permissions set to 000 the FPA script will fail to complete. Eventually the script will only display the top info (header) box of the script page. Removing the 000 permission directories or altering the directories permissions to 755 solves the issue.

Error related to issue:
[Mon Nov 26 23:21:00 2012] [error] [client 123.123.123.123] PHP Warning: readdir() expects parameter 1 to be resource, boolean given in /home/sites/mysite.co.uk/public_html/fpa-en.php on line 1484

Tested
The script does fail as described.

Needed:

option 1
gracefully make the directory search ignore directories that are set to 000 and not try to read them. 

Option 2
make script not fail on 000 set directories
make script keep count of the number of 000 set directories and provide a indication in the FPA results page. The PHP environment or system environment info boxes would be a good place to indicate this. Adding this to the generated results for forum posting would also be good to do.

**Comment by frostmakk** [comment]
Fixed in 1.2.7 release.
