### ISSUE TITLE
Need a more accurate way to determine if there is a possible ownership issue.

### ISSUE THREAD

**Issue by PhilD13** [ForumPostAssistant/FPA#17]
There is code to attempt to test for possible file/directory ownership problems. This code has never worked well or entirely properly on all servers.
Results are displayed something similar to this:

suExec No        PHP suExec No        Custom su Yes        Ownership Probs No

The code starts at about  line 1269
 /*\* API and ownership related settings

**Comment by RussW** [comment]
If the new GUI method of determining Permission or Ownership issues works for everybody, then I'll introduce this method to the post output section as well and this very old issue might then get closed :D

**Comment by RussW** [comment]
new method implemented in v1.6.0 - closed
