### ISSUE TITLE
Look for config setup info that may be commented out

### ISSUE THREAD

**Issue by PhilD13** [ForumPostAssistant/FPA#19]
When pulling values out of the configuration.php file, it ignores if a value is inside a comment. I have one file that I can update for use locally or on the production server, so I have commented out a line that reads:
Code:
// public $host = 'localhost';

This line was immediately before the line used by the system.

For this reason, I wasn't getting any of the database info, since my hosting provider uses a db running at a different url.
Once I changed the order of these lines, then fpa picked up the correct value.

It should be easy to have preg_match detect a line starting with '//', but it might require removal of all /\* ... */ comments before extracting information.

Hope this might help others who want to see info that is not coming thru.

WebMuse

**Comment by frostmakk** [comment]
// commented lines taken care of in 1.4.0 release.

**Comment by frostmakk** [comment]
Issue fixed in v1.4.5 by including the file.
