### ISSUE TITLE
FPA Rewrite

### ISSUE THREAD

**Issue by PhilD13** [ForumPostAssistant/FPA#20]
Hey @organization/Development

Outline of what s to be done.
- Name remain: FPA
- Change Version number to 2.0.xx
- remain able to detect any version of Joomla from 1.0.xx to current versions.
- Basic single file structure remain for FPA, or if decision is to go to multiple files, an easy way to install and uninstall the files.
- remove any code that was intended for other posting uses and we do not need to use such as bug report mode (intended to create a report for reporting Joomla bugs) and maybe diag mode. The modes are listed at the top around line 30. Don't know if Developer mode is needed though it may be handy.
  - enable a multi-language in FPA  so users can see results in their own language
- Use transifex for translation - I will post some info about what we currently have for transifex and integration.
- the generated forum code should always be presented in English to the forum so that part would not be translated.This is another reason to group the code. I also think this is a very good idea to pursue.
- Keep current output layout as it is easy to find related info.
- Improve the BB code output to make it easier to read
- BB code still has to fit a forum post in length 
- Add color to BB code 
  - red - danger
  - orange - warning (may be bad or unable to determine)
  - green - OK
    will make easier to scan for issues
- code is scattered about in various parts - reorganize and group all code into blocks to make easier to read and follow
- all code used to generate the bb code (the generated forum code) should be grouped. This would include the section for optional information and selection of parameters in the drop down (Show the Forum Post Assistant) area that would be included in the forum posting.
- clean up comments and add new where necessary for clarity
- the FPA for some reason is no longer properly displaying the initial top pink title box  which also contains the link to delete the script. The box should always be on display at the top of the page, but now it appears to only initially display and then is replaced with the other main parts of the script once the script is done running. This should not be happening. 
- Improve script  delete (removal process) if it needs to be improved
- some parts have always been suspect in the information that is returned or determined which should be fixed. I think mainly in the area of determining SUEXEC and custom SU for the server. Some servers such as Lightspeed, and Mediatemple servers do not necessarily use Apache SUEXEC modules, but rather custom ones.
- Accurately determine third party plugins, templates, modules, components and their versions
- Make results more colorful on the results display screen
  - red - danger
  - orange - warning (may be bad or unable to determine)
  - green - OK
- Fix the section boxes as some don't fit properly with the results displayed within them.

FPA fails when encountering directories set to permissions of 000 which some people may do to suspicious directories to prevent access. Make the FPA take note of these 000 permission directories, listing them in the report and not fail.

Please add suggestions notes, discussion

Phil

**Comment by PhilD13** [comment]
Please use branch FPA_2.0 for development and rewrite. Once rewrite is done, we can move to translate the 2.0 version.

**Comment by mandville** [comment]
Is this suitable for vel posting?

**Comment by PhilD13** [comment]
The stuff in the FPA-2.0 is just a copy of the FPA (en-GB) placed in a new directory so that we don't mess up the existing FPA files that the forum is linked to when working on rewriting the script. I will change the readme on the directory to reflect this in a bit.

On a related note , don't use the FPA contained in the multilanguage or multilanguage-development. Those are old FPA versions and are there as a basis to work on translations. This was what elkuku worked on at one point.

**Comment by PhilD13** [comment]
Should I make the directory name FPA_2.0-Development? so it is clear it is a development version?

**Comment by btoplak** [comment]
Yes, I think "Development" suffix would be wise.

I will make a fork to start some work on a clean file, in sense of full rewrite.

**Comment by PhilD13** [comment]
I changed the name of the directory to FPA_2.0-Development and changed the readme file for the directory and also changed the FPA file to fpa-en-2.0 so as not to be confused with the existing fpa file used in the forums. This should make things easier to test and compare also.

The fpa-en-2.0 is the file that should be used for the rewrite.

**Comment by sozzled** [comment]
@ForumPostAssistant/development @ForumPostAssistant/advisors-reviewers

I think that the work done in https://github.com/ForumPostAssistant/FPA/tree/2020-UI-Facelift  supersedes this activity has added 2,000+ lines more code and, to a large extent, incorporates many of the design objectives that were identified for FPA 2.0.  I recommend that the "facelift" fork replaces the FPA_2.0-Development and becomes, in effect, version 2.0.

**Comment by RussW** [comment]
Based on the above, I think we should close this issue, as mentioned by @sozzled, against the new https://github.com/ForumPostAssistant/FPA/tree/2020-UI-Facelift branch and I will open new issues for the versioning & codename discussions.
