### ISSUE TITLE
FPA translation

### ISSUE THREAD

**Issue by PhilD13** [ForumPostAssistant/FPA#21]
Hey @organization/Development

This is where we should discuss the FPA translations.
- use transifex
-  see the FPA multilanguage-development directory for scripts for working with transifex etc.

**Comment by elkuku** [comment]
Why are there two multilanguage branches?

**Comment by elkuku** [comment]
See also  https://github.com/ForumPostAssistant/FPA/issues/29#issuecomment-336697131 and several other issues about multilanguage stuff

@mandville could you please explain what kind of help it is that you "want" (especially after **all these years** that have past since this issue was opened...)

**Comment by RussW** [comment]
closed due to age and recent developments
