### ISSUE TITLE
j3.5 version check missing

### ISSUE THREAD

**Issue by mandville** [ForumPostAssistant/FPA#24]
sometimes will not show j3.5 version, just shows 
Joomla! Instance :: .- ()
Joomla! Platform :: Joomla Platform 13.1.0-Stable (Curiosity) 24-Apr-2013

eg
http://forum.joomla.org/viewtopic.php?f=714&t=917241#p3386295

**Comment by btoplak** [comment]
It seems like another thing needs fixing after 3.5 ... I will check that out later on today.

**Comment by btoplak** [comment]
should be fixed in df32139d11ac11e832d37cfb602247be46b17157
