### ISSUE TITLE
How to add new tranlation of FPA?

### ISSUE THREAD

**Issue by wojsmol** [ForumPostAssistant/FPA#29]
Hi I wont to use FPM on Polish Joomla! Forum and I have 3 questions:
1. Whether translating the FPM isd how supported?
2. If yes then how to add new language?
3. I see few issues related to localised version of FPM is open. Is there any ETA to fix tis issues?
wojsmol (Polish Joomla! Forum Moderator)

**Comment by frostmakk** [comment]
The multi-language project seems to have dried up some time ago, and I'm unsure whether the people involved  have the time and energy to pick it up again.
If this project is to be brought back to life, there are several decisions to be made as I see it.
Do we still use [transifex](https://www.transifex.com/opentranslators/fpa/) , and who maintains it? Do we go for a single file solution where a translated version is released in its own branch, or a multi-file solution where the user can select the language?
Do we translate both the form and the forum post output? A translated post output will have limited audience in the local forum, and will not be appreciated in the main forum.
Several of the language strings are used both on the form and in the post output, so there is work to be done if only the form should be translated.
I will leave all these decisions to the owners of this project.

If you want a local solution for the Polish forum now, my suggestion would be as follows:
Start with the Polish translation file located in the g11n folder in multilanguage-development branch. Update/complete a local copy of this file.
Write a small script that replaces the language strings. Put the translated file somewhere, and announce it on the Polish forum.
Whenever the FPA is updated, run the script again, and replace your local file.
You should also make it clear to the users that this is not an official release from the FPA project.

**Comment by mandville** [comment]
translations have been purely community dependent and are repeatedly request. for simplicity it is usually best to keep everything in one file

**Comment by mandville** [comment]
there is now a crowdin page
https://crowdin.com/project/miscelleanous

**Comment by RussW** [comment]
closed due to age and recent developments
