### ISSUE TITLE
Reducing the 20K character limit for pasting the FPA report on the forum

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#36]
Several of us have flagged the 20K character limit as an issue.  It's quite probable that this limit will not be relaxed by the forum administrator(s) (and for very good reasons) and it's therefore likely that the FPA V2 activity will have to accept that the 20K character limit will remain a constraint.  Given that this issue has been identified as an important one, I think it may be useful to have a discrete discussion on ways that FPA V2 can reduce the amount of BBcode to keep the number of characters under 20K but, as far as possible, provide key information that may assist us in helping those who use the FPA.

Obviously, the [COLOR] tags contribute substantially to the amount of BBcode "text"; other BBcode markup tags (e.g. [U], [QUOTE] and [SIZE] also add to the weight).  These formatting codes are visually important and I believe they should be retained.

As we've discussed elsewhere, if we can find some easy ways for gumby-newbies to selectively obtain parts of the FPA report suitable for posting, then all the better for FPA V2.

I prefer, from the "helper's perspective" to see as much information about a problem site as possible.

Although not always the cause, plugins can contribute to problems ... especially enabled plugins.  What about FPA V2 offering the choice of displaying **enabled** plugins or all installed plugins?

Similarly, again while not necessarily the cause of problems, what about offering the choice of displaying **published** components vs. all components?

I think we can suggest other switcheroonies to reduce the volume of BBcode generated by the FPA on extension-bloated J! websites.

**Comment by RussW** [comment]
good call, will be looking in to this and as many options as possible as we proceed, all idea's welcome at this point

**Comment by RussW** [comment]
Just thinking out-loud....  Apologies for a potentially "dumb possum question", it's been years since I actually used the forums and am certainly no-longer an Admin or Mod in any of them.

_Is there an area or single post in the forum that is/can be hidden from users for testing/reviewing/proof-reading the BBCode and potential solutions?_

**Comment by mandville** [comment]
Not that we all could see. 
I could or ask for a limited forum for us to test.

**Comment by frostmakk** [comment]
I use a local "translator" to view the output, but you could always create a new post, paste the code, hit preview, and discard the post without saving.

**Comment by mandville** [comment]
I have requested a hidden limited user forum. Watch this paint dry.

**Comment by RussW** [comment]
Thanks for that, it will be a little time before we get in to the "guts" of it, so there is no panic

**Comment by mandville** [comment]
new forum available . i posted link in the testing folder

**Comment by RussW** [comment]
### Problem : 20K character Limit On Individual Posts
This is going to be a toughie folks! What's good for the goose _(trouble-shooter)_, isn't necessarily going to be good for the gander  _(end-user)_ or might just cause more problems than the user was observing in the first place... All bright idea's welcome and will be considered...

Idea's for discussion to reduce the BBCode output but still provide useful information to those assisting trouble-shooting, whilst not making it too difficult to end-users to complete the relevant taks


#### Potential Resolutions
- **reduce the BBCode output** : _potentially reduces diagnostic info_ _(**not a great plan**)_
- **reduce the amount of colouring** : _only highlight [red] error or problematic items_ _(**clean solution**, but may not save many/enough chars...)_
- **break the output in to multiple sections** : _end-user confusion and difficulty posting all relevant information_ _(**do-able, but...** see below)_

<hr />

#### Thinking Out-Loud! 
- **break output into multiple textboxes in the "Post Output" tab**
  - **1a)** _Multiple Textboxes in "Post Output Tab_ 
  each textbox contains info from each _`Section`_ and have a separate _`Copy Button`_ for each textbox to be posted in to different (subsequent) posts/replies. 
  _**Difficulty** : Try to explain to an end-user how to post this!_ 

  - **2a)** _Single Textbox in "Post Output" Tab & `Copy Button`_
  only offering the `basic/core information section` information. 
     - provide no additional textboxes in the "_Post Output_" tab but provide a simple _`Copy Button`_ in the Visual Report sections for the additional information to be posted in to subsequent posts/replies. 
  _**Difficulty** : Try to explain to an end-user how to find the data and then how to post this!_ 
   
<hr />

## BRIGHTER Idea's?

**Comment by sozzled** [comment]
I don't have too many other suggestions.  As an example of some of the things we're dealing with, see this forum discussion https://forum.joomla.org/viewtopic.php?f=715&t=962145#p3525243

It took the poor guy _**eighteen**_ attempts to [eventually] submit his "entire" FPA report (complete with "smileys on" by the way.

Although off-topic here, instructing people how to post the BBcode is just not getting through:  here's a cse where the person had _**no idea**_ how to follow the instructions:  https://forum.joomla.org/viewtopic.php?f=708&t=962097#p3525084

Needed a 1-2-3-4 comic book approach to instructing the person to compose their FPA report suitable for posting on the forum.

**Comment by RussW** [comment]
I can only comment with a quote from one of my favourite comedians, Ron White;
https://www.youtube.com/watch?v=UQv7Tr8HbGE

I was hoping that the new "**Tabbed**" FPA section may assist with the process, now all we need to do in "_bang-heads_" and come up with idea's to overcome the 20K limitation or to ease the posting process.

**Comment by sozzled** [comment]
See my ideas posted in other areas about toggling on/off including/excluding some sections of the report or some extensions (e.g. "enabled" vs. "disabled" ones).  With caveats, of course, but removing parts of the report might be a way out?  It's bloody difficult because we're dealing with gumbies who don't know their ISP from their telco or their webhosting provider from their witch-doctor.

**Comment by sozzled** [comment]
I had another idea:

If the FPA _**does**_ generate more than 20K characters (including all the BBcode), how about displaying the following message on the FPA page:

> Your report has been generated but it contains more than 20,000 characters which may be unsuitable for posting on the forum.  Would you like to change the FPA settings—exclude some parts of the report—in order to try to reduce the character count?  Your FPA report exceeds the forum character limit posting restriction by _n_ characters.

Obviously the message could be more comprehensive but, unless someone's willing to produce a 10 minute instructional video on how to use the FPA and all of the FPA's configuration settings, the next best thing is to write a 64-page instruction manual.

**Comment by mandville** [comment]
not wanting to udno frostmark work but how many characters saved if we dropped the colour coding to the extensions?

**Comment by frostmakk** [comment]
20 characters pr extension.

**Comment by sozzled** [comment]
Each colour markup consists of`[color=#xxxxxx][/color]`which means that there are 23 characters involved.  If there are, say, 100 extensions listed in the FPA report, that's 2,300 "extra" characters (a significant proportion of the overall data required to format this information on the forum).  I haven't crunched the numbers but, my guess is, 30% of everything produced by the FPA BBcode generator is "markup" code.

Using colour to differentiate between core and third-party extensions is, from the _**forum user's**_ POV helpful.  Separating core from non-core into discrete areas of the FPA report (and display those areas without colour-coding) will add overheads to the logic.

I've been wrestling in my mind about the use of the 1/0 (published/enabled vs. unpublished/disabled) thing as well as the "default template" identifier (the template that's underlined).  Underlining to imply the name of the default template is helpful.  Underlining to imply that an extension is published would not be helpful.  Underlining or bolding, to differentiate between core and third-party extensions (whilst reducing the character count by 16 characters per extn.) may become to confusing from at the end-point (on the forum).

The problem is that, as Joomla continues to expand in terms of its constituent parts (and as people install all kinds of useful and useless 3PD optional extras) the FPA reports grow larger and they often (not inevitably, but often) hit the 20K character limit imposed by the forum.

**Comment by sozzled** [comment]
@RussW FWIW, if you think we wouldn't be wasting our time gas-bagging by telephone or video-conference to brainstorm some ideas, I'm up for that.  If it's to be a group video-conference thing (given the time differences involved) then probably not. (I only video conference via Skype, BTW).  I'm fairly easily privately contactable.

**Comment by frostmakk** [comment]
I have used [color=Brown][/color] and [color=Blue][/color], and that shaves it down to 21 and 20.
:-)

**Comment by sozzled** [comment]
I produced a mock-up of a FPA report without any colouring for the installed extensions.  https://forum.joomla.org/viewtopic.php?f=804&t=962201

I used italicising to "highlight" third-party extensions.  It looks a bit crappy but I hope it gives you an idea.

The effect of removing the [color] tags is a 25% savings on the BBcode (from 13.3 Kb to 9.96 Kb).  A further saving can be made by removing the [color=#000000]...[/color] tags from the FPA because they make no difference to the way the information appears on the forum.

**Comment by frostmakk** [comment]
You have used a very outdated version (1.3.0) to test with. The BBCode has been optimized since then.
But, never mind.
It is probably a better solution to group the extensions in the output. Then the group header can tell what the colors do today.

**Comment by sozzled** [comment]
It doesn't matter a lot what version of the FPA I used; the point of the exercise was to demonstrate what might happen if we removed 25% of the weight of the post (in terms of the number of characters) by removing the colours for extensions and replaced the 3rd-party extension colours with italics.  It's just a made-up example using some real data.

This method (to remove the [color] tags) is OK or not?  In other words, do we need [color] tags for core extensions or not?  Can we highlight 3rd-party extensions only with italics or do we also need [color] tags?

**Comment by frostmakk** [comment]
Been looking into the possibility of grouping the extensions in the output.
This greatly reduces the number of characters used on color coding. I kept the colors, simply because i like them. It's only two tags per group anyway.
If you want to review this version, you will find it in the FPA_FM branch.
I have posted a sample output at https://forum.joomla.org/viewtopic.php?f=804&t=962815
This sample clocks out at 15570 characters compared to 20199 characters without the modifications.

**Comment by sozzled** [comment]
I realise that it may not seem to add _**significantly**_ to the overall weight of BBcode, but the use of named colours (e.g. `blue`, `red`, `green`, `orange `and `brown`) instead of 3-digit HEX colour values may help even if only a little bit.  Even though we would only be saving a few bytes, every _**unnecessary**_ byte that we save in reducing the total quantity of BBcode may help.

Therefore, instead of using the named colours (although `red` is shorter than `#f00`), consider the following:

`blue` becomes `#00f`
`green` becomes `#484`
`orange` becomes `#f80`
`brown` becomes `#a22`

I estimate that the overall total savings might be only a couple hundred bytes—not much—but it may be worth considering.

Comments?

**Comment by fcoulter** [comment]
The grouping of extensions by core and 3rd party is a really good idea, it increases the clarity of the results in addition to saving on characters, I vote yes for this.

**Comment by mandville** [comment]
https://github.com/ForumPostAssistant/FPA/pull/44 for testing
