### ISSUE TITLE
naming releases

### ISSUE THREAD

**Issue by mandville** [ForumPostAssistant/FPA#37]
should we?

**Comment by RussW** [comment]
That's funny, I was only thinking that yesterday after chatting with a Aborignal (indigenous AUS people) friend and remembering the Joomla! Swahili naming convention.

I was thinking that only Major & Minor (_x.y_.-) releases might be named though, not the patch (-.-._z_) or the dev ( x.y.z-_[dev/alpha/beta/rc]_) releases to save on coming up with too many names.

I certainly have nothing against the idea.  Thought's on a convention?

**Comment by sozzled** [comment]
I have no idea how koori languages (there are 150+ of them) relate to Swahili?  If you're talking about codenaming, it's probably a waste of time.  I get the idea, you could call FPA v2.0 "Canberra" ([Canberra being an aboriginal word that has one of two meanings](https://www.etymonline.com/word/canberra)).

I would suggest the following naming convention:

for all α, β, RC versions, these should **_only_** apply to new major/minor releases:  e.g. _x_.0.0-alpha, _x_._y_.0-RC, etc.

Dot-point/patch releases for after the new major/minor has become stable.

**Comment by RussW** [comment]
FPA always has, and as far as I am concerned, will continue to employ the ISO Standard Software Development/Engineering Release Management designation of   _**major.minor.patch-devlevel**_, with the "_devlevel_" also utilising the ISO Standard designations of "dev, alpha, beta, rc".

I believe, that these designations should continue to be applied to the _patch release level_ as well as the major & minor releases.  _**However**_, from my experience, the traditional Software Development/Engineering practice is to NOT publicly offer _devlevel releases_ that are considered to be alpha or beta except to a select list of Q&A or Test members. 

This process & designation is also bourne-out by the Github framework, with the use of branches, especially the "master branch" being the alpha & beta versions (and only downloadable via the branch) whilst RC and Final revisions are available as "Official Releases".

So in essence this means that the "_**Releases**_" Tab should only ever contain **RC** & **Final** releases for download, and "_alpha_ & _beta_ versions can only be found in the main branch and only downloadable from there.

As far as the **Release Name / Codename** option, **_I personally_** still think it's a bit of fun and a  lively idea, of which I also feel FPA could do with a bit of "loosening-up" & "fun value" being added to it.

**Comment by RussW** [comment]
Just thinking out-loud....  _(I know, I have a bad habit of doing this and putting my foot in my mouth at the same time)_

_**BUT...**_ I reckon if we're going to go for this (of which I agree with @mandville  and am in favour of) it should be something _entertaining_ like;

- **Old-School Cartoon Characters** : Wile E. Coyote, Bugs Bunny, Roger Rabbit or something just as inane and silly, or;
- **Well Known Famous Nicknames** : Donk - Croc Dundee, Agent99 - Get Smart, Hot Lips - MASH, you get the picture

_There's no reason for it to be serious and staid_.

**Comment by mandville** [comment]
why go mainstream, an extension we use on vel is codenamed after our dogs,

**Comment by RussW** [comment]
Idea's for the naming convention?

How many dogs do you have @mandville? Enough for maybe 5-6 or more major/minor releases?

My suggestions at the moment are simply;

- Old School Cartoon Characters
- Well Known/Famous Nicknames
- Someone looks out the window and we use what they see (I see heaps of Aussie wildlife and sealife where I live)
- Stars/Constellations
- randomly pick something at the time of release

**Comment by mandville** [comment]
i have 2, fiona has 1, and why be canine, what about felines, or fishkins ?

**Comment by RussW** [comment]
My Chocolate Lab is "_**Georgie Girl**_" (after the song) and there's a "_**Kookaburra**_" ([it's an Aussie bird whose call sounds like it's laughing](https://en.wikipedia.org/wiki/Laughing_kookaburra)) that visits me most days and was named "_**Podge**_" by my boys because they are cuddly little things that always look a tad on the overweight side.

**Comment by fcoulter** [comment]
I have several ex-pets as well (ie mean they have ceased to be) so no danger of running out.

The only thing about using pet names is that sometimes they are used as security questions for account recovery, maybe it is the sort of information that we should be wary of exposing. Or is that being too paranoid even for me?

**Comment by RussW** [comment]
@fcoulter, that's actually more than a _fair and reasonable_ concern.

Let's think again, or just go with a random naming at the time of release, but that would require additional input at that time.

**Comment by fcoulter** [comment]
Or something fairly non-personal like shades of colour: beige, lilac, buttercup yellow

**Comment by mandville** [comment]
just not latin names for flowers, that would kill the 20k limit,,,

**Comment by sozzled** [comment]
If I had a preference for codenames for versions, I would use old TV westerns (although they may have "violent" connotations):  e.g. Gunsmoke, Bonanza, Cheyenne, Sugarfoot, Maverick, BrokenArrow, WyattEarp, CaseyJones, Cisco (or CiscoKid), LoneRanger, Rifleman, RinTinTin, Rawhide, etc.

**Comment by fcoulter** [comment]
How about varieties of cheese? Wensleydale, Gorgonzola, Cheddar, Stilton, Camenbert?

**Comment by mandville** [comment]
I'm allergic to cheese.

**Comment by sozzled** [comment]
This was a big problem that I had with the Kunena project (when I was active with it).  The idea was that codenames (following some theme) should be decided when development began on a new version; **_not_** at the time the new version was released to the public.  While we were able to agree, generally, on the theme (although the theme changed a few times) and we were able to "vote" from some suggestions submitted within the project team, the codename was rarely seen in the code until the day the release was made public.

So, I really don't much care about codenames unless there's a serious intention to use them **_during_** the build of a new version.  [This was the approach taken by Microsoft](https://namingschemes.com/Windows_codenames):  e.g. Chicago became Win95, Memphis became Win98.  Of course, a codename is only a work-in-progress name that's "fun" or an in-joke for those who are working on the project.  Outside the team, the product-name and version number is all that anyone really cares about.

(off-topic) I see there's a new release of J! (J! 3.8.8).  Looks like I have a bit of testing work ahead of me ...

**Comment by RussW** [comment]
I've added a constant **_RES_NAME** and _**temporarily named it**_ "**Emu Creek**" as that's my last destination and we haven't got a scheme nailed down yet.   

**Name Suggestions for the first release welcome...**

**Comment by mandville** [comment]
if you picking animal named towns, i always liked (across the water from you ) Waikikamukau

**Comment by RussW** [comment]
@mandville  ...  "Waikikamukau"  it is then....
