### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by brianteeman** [ForumPostAssistant/FPA#39]
What is the copyright of this as I cant see one anywhere

**Comment by RussW** [comment]
Quite what are you looking for regarding "copyright"?

There is a minor statement in the footer and within the "Contributors & Developers footer section.

**Comment by brianteeman** [comment]
a clear copyright statement at the top of the file - just as in joomla and the presence of a copyright.md file here in the repo

**Comment by sozzled** [comment]
@RussW copyright notices are required for GPL purposes.  There's a recommended approach to formatting these things.
`/**`
` **  @package 				Joomla! Forum Post Assistant`
` **   @version 				FPA x.y.z`
` **  @copyright 			Copyright (C) yyyy, <personal id/business and website>`
` **  @author				<original author name>`
` **  @license				GNU/GPL, see LICENSE.php`
`/**`
(or something like that) as a minimum, I guess.

Note, dates should never be abbreviated to numeric-only format.  For instance, 3/10/2018 could mean 3-Oct-2018 or 10-Mar-2018.  I write dates as d-mmm-yyyy to avoid any confusion.

**Comment by mandville** [comment]
currently i can see 
```
  **  @package Forum Post Assistant / Bug Report Assistant
- **  @version 1.3.9
- **  @last updated 14/01/2018
+ **  @version 1.4.0
+ **  @last updated 17/05/2018
  **  @release Beta
  **  @date 24/06/2011
  **  @author RussW
```

**Comment by sozzled** [comment]
That's what I see, too.

I'm not proficient at using GitHub to make changes (even ones that need to be pulled into the master) and I'll leave that to those who have such skills.  Even a simple change, as the one @brianteeman  recommends, could be made (either by him or someone else) and this matter will then be resolved.  It's just a SMOP—a small matter of programming—(as my late father was fond of saying). :)

**Comment by RussW** [comment]
_your wish is my command_

new copyright notice will be added in due course

**Comment by RussW** [comment]
**Added GNU/GPL 3 License to the project** (click on LICENSE file to view summary and license) at [commit](https://github.com/hotmangoDevelopment/ForumPostAssistant-v2-2018/commit/30441a0aa9afdbc8a931c1695bc129c96885aef7)

**Updated docblock and moved to the top of the script**
removed invalid elements, updated copyright, added copyright at [commit](https://github.com/hotmangoDevelopment/ForumPostAssistant-v2-2018/commit/c9c31ce7f764f46a7bfccbd98c9e14c0a3965ffc)

_If everyone is happy, I'll close in due course_
