### ISSUE TITLE
Missing Extensions Should Account for Upstream PHP Changes

### ISSUE THREAD

**Issue by mbabker** [ForumPostAssistant/FPA#40]
- `ext/mysql` was deprecated as of PHP 5.5 and removed in PHP 7.0
- `ext/mcrypt` was deprecated as of PHP 7.1 and removed in PHP 7.2

When the FPA is run on PHP versions where these extensions are no longer available, the FPA should not report them as potentially missing.  This can be misleading to end users or to individuals providing support on the forums as it may be suggested to someone they need to install these dead extensions.

**Comment by frostmakk** [comment]
Agree. These, and several other PHP related settings/extensions should be evaluated in the preparations of the 2.0 rewrite of the FPA.
While I have your ears:
Mcrypt is still listed as a Joomla technical requirement. https://downloads.joomla.org/technical-requirements
When is it required, and when is it not?
Is it before a certain Joomla version, or is it Joomla running on PHP before v7, or...?

**Comment by mbabker** [comment]
Sometime after we started testing PHP 7.1 compatibility did we go through the effort to decouple the one point in the code that had a hard mcrypt requirement.  Definitely since 3.8.0 that's not true anymore (I think that code got replaced with an OpenSSL adapter if I remember right, it was in the two factor authentication stuff).

**Comment by RussW** [comment]
@frostmakk , Sveinung can this be assigned to you to update in the v1 release when you have the time? 
and as we progress with v2 it will be incorporated there as well.

@mbabker, Michael if you are interested in having some input in to the currently planned FPA v2 update, let me know and we can have a chat.

**Comment by frostmakk** [comment]
I'll look into it.

**Comment by frostmakk** [comment]
Implemented in v1.4.1
