### ISSUE TITLE
Add noindex meta tag to output

### ISSUE THREAD

**Issue by fcoulter** [ForumPostAssistant/FPA#41]
Please add 

`<meta name="robots" content="noindex">`

to the <head> output, it might save a few people some trouble, see .google.com  search?q=inurl::+fpa-en.php

Even though most of the entries have thankfully been deleted now, Google has helpfully cached the output in some cases.

I think that the issue is that, even if people are only leaving up the fpa for a short time (so are not doing anything silly), if Google happens to crawl it during that time then the results will be indexed and cached.

content="noindex" ensures that the results are not indexed or cached.

**Comment by RussW** [comment]
added  noindex, nofollow, noodp, nocache, noarchive, will be included in the next release
commit :  https://github.com/ForumPostAssistant/FPA/commit/ea87de2ca2252597630a645fc534a94f8db62b83

**Comment by frostmakk** [comment]
Implemented in v1.4.1
