### ISSUE TITLE
FPA report shows deprecated PHP includes when using PHP 7

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#46]
See Joomla forum post by @mbabker https://forum.joomla.org/viewtopic.php?f=706&t=962427&p=3533014#p3527241 and further on in that discussion.

Tested FPA 1.4.3 (current release) here:   https://forum.joomla.org/viewtopic.php?f=804&t=962167#p3529609

See my comments on @mbabker's observations with FPA here: https://forum.joomla.org/viewtopic.php?f=706&t=962427&p=3533014#p3533014

**Comment by frostmakk** [comment]
See Issue #40

**Comment by sozzled** [comment]
Thanks.  Pls merge this topic with #40 (it may provide some additional background).
