### ISSUE TITLE
Change [DO NOT BUY OUR KITCHENS] to something more meaningful?

### ISSUE THREAD

**Issue by fcoulter** [ForumPostAssistant/FPA#47]
We have had a post in the forums from a user who assumed that the FPA output [DO NOT BUY OUR KITCHENS] meant that the site was hacked - it is a website selling kitches so you can understand why he assumed that it was a malicious message: [https://forum.joomla.org/viewtopic.php?f=714&t=964306](url).

The message is confusing to users, no-one knows what it means (including me) so why not change it to something that makes a bit more sense?

**Comment by frostmakk** [comment]
This is a forum issue. Nothing to do with the FPA.

**Comment by mandville** [comment]
Fiona . If you look in the mod forum.there is a discussion on this particular word filter.

**Comment by sozzled** [comment]
I have responded on the forum:  https://forum.joomla.org/viewtopic.php?f=714&t=964306&p=3535194#p3535194

**Comment by fcoulter** [comment]
OK yes I see your discussion there, I totally agree with your viewpoint.
