### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach() in <site-root>/fpa-en.php on line 6452

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#53]
See forum topic/post at https://forum.joomla.org/viewtopic.php?f=710&t=968910&start=30#p3557078

Unable to reproduce this error on any of my test websites (using PHP 7.2).  Would anyone have any ideas how this situation occurs.

As far as the FPA report is concerned, it does not seem to have caused the FPA to fail but it's possible that the report may be ambiguous.   I cannot verify if this is a coding error.  Because we do not have a forum category at the J! forum, I am opening the matter for discussion here.  This may not be an error.  I just don't know.

Line 6542 is contained within a for-loop that looks recursively at site plugins.  That's the only other information I can offer at this moment.

**Comment by sozzled** [comment]
Not an isolated example.  See also the following forum topics where this error message occurs

https://forum.joomla.org/viewtopic.php?f=710&t=969043&p=3556088#p3556088
https://forum.joomla.org/viewtopic.php?f=706&t=967491&p=3555651#p3555651

**Comment by frostmakk** [comment]
Thanks for reporting.
The error occurs on sites without library extensions. I forgot to put in a trap for this eventuality.
The output from the FPA is not affected.
This will be fixed in the next release.

**Comment by sozzled** [comment]
Thanks.

**Comment by frostmakk** [comment]
Issue fixed in v1.4.8
