### ISSUE TITLE
KUDOS: Not an Issue, but couldn't figure out where to send this.

### ISSUE THREAD

**Issue by jzeevi** [ForumPostAssistant/FPA#61]
I stumbled across FPA trying to debug a site problem and wanted to say thank you to the developers. It took me less than 5 minutes to figure out what was wrong using the script.

THANK YOU!

**Comment by mandville** [comment]
Hello and thankyou.
There is a public discussion forum at
https://forum.joomla.org/viewforum.php?f=806
