### ISSUE TITLE
suggested press release

### ISSUE THREAD

**Issue by mandville** [ForumPostAssistant/FPA#65]
Over a decade ago, a developer launched a suite of tools to help Joomlers diagnose issues with hosting, the installation and other related items. 
Part of this suite was what is now known as the forum posting assistant or FPA. 
This standalone tool created by Russ Winter has become such an integral part of the joomla world that it is used as the go to item for anyone with issues on their site. 
You can not only find out the state of your server, possible conflicts that cause your site issues, but The tool will run even if Joomla isn't installed properly.

Russ was then joined by Fiona Coulter, Claire Mandville and Phil DeGuy from the security forum team to develop the tool futher. with the aid of "Frostmak" coding, with "Sozzled" and Webdongle testing and suggestion the current stable release 1.5 available on Github now has full easy to documentation and has helped countless joomlers.

This month Russ worked on some of the outstanding issues and with the aid of the team are on the verge of releasing the latest (un named) version. 
This version has fine tuned the following

* Print to PDF, so you can pass the output to a 3rd party without leaving the script on your site, 
* Allow the FPA to check its the latest version.
* FPA self destruct features auto-delete 7 days after installation.
* Hosting Confidence Level to indicate how worthy of running joomla your server is. 

If you wish to download the FPA and give it a run for its money then go to ...

**Comment by sozzled** [comment]
I'm happy for my real name to be used as part of the press release.

As a possible improvement to the appearance of the release, I would suggest the following (very minor) changes.

----------------------------------------

Over a decade ago, a developer launched a suite of tools to help Joomlers diagnose issues with hosting, the installation and other matters associated with Joomla!  Part of this suite was what is now known as the _Forum Posting Assistant_ or FPA.

Conceived by Russ Winter both as a standalone tool and as a means of producing a report that integrates into the [Joomla Forum](forum.joomla.org), the FPA has become such an integral part of the Joomla! world that it is used as the "go to" item for anyone with website problems.  You can not only find out the state of your server, possible conflicts that cause your site issues, but the tool runs even if Joomla! isn't installed properly.

Russ was then joined by Fiona Coulter, Claire Mandville and Phil DeGuy from the security forum team to develop the tool futher, with the aid of "frostmakk", Michael Russell and "Webdongle" coding, testing and offering their help.  Our combined efforts have helped untold numbers of Joomlers.

This month Russ and the team worked on some of the outstanding issues and we're on the verge of releasing a new version that incorporates

- Print to PDF, so you can pass the output to a 3rd party without leaving the script on your site,

- Allow the FPA to check its the latest version.

- FPA self destruct features auto-delete 7 days after installation.

- Hosting Confidence Level to indicate how worthy of running Joomla! your server is.

If you would like to try out the FPA and give it a run for its money—it's free, by the way—then go to ...

**Comment by mandville** [comment]
i fiddled with that line and found that it was tongue twitter mentally
**  integrates
into the Joomla Forum, the FPA has become such an
** integral
part of the


C Mandville
Joomla! Vulnerable Extensions List Team Leader
Joomla Security Strike Team Member
Joomla Trademark Team Leader
Unless indicated - this email discussion is not to be shared beyond the
original recipient

**Comment by sozzled** [comment]
Then, instead of [the phrase] "integrates with the Joomla! Forum", how about "you can use with the Joomla! Forum"?

**Comment by RussW** [comment]
Incorporating the above suggestions and adding a little more "fluff", maybe something like the following, I've left the "Print to PDF" in the list, but at the moment it's not there as a unique function, just better styling for the normal "Browser Print" function.

As for the versioning and naming, I'm inclined to think as this is still using the original v1 functions and post output, mostly just UI/UX updates that maybe we stick with v1, just skip to the next minor release.  IE: **v1.6.0** and stick with the current nickname of : **facelift**

> Over a decade ago, a developer volunteering in the Joomla! Security Forum launched a suite of tools (Joomla Tools Suite) to help Joomlers diagnose issues with hosting, the installation and other matters associated with Joomla! Part of this suite was what is now known as the Forum Post Assistant or FPA.

> Conceived by Russ Winter, to function as both a standalone tool and as a means of producing a report that integrates into a post on the Joomla Forum, the FPA has become such an integral part of the Joomla! world that it is used as the "go to" tool for anyone with website problems. You can not only find out the state of your server, any possible conflicts that cause your site issues, but the tool also runs even if Joomla! isn't installed properly.

> Russ was then joined by several well-known Joomla! community members, Fiona Coulter, Claire Mandville and Phil DeGuy from the security forum team to further develop the tool, with the aid of "frostmakk", Michael Russell and "Webdongle" coding, testing and offering their help. 

> The combined talent, dedication and efforts of the FPA project team have helped untold numbers of Joomlers over the years, not only making it easier and simpler simpler for Joomla! beginners and veterans alike to get get help when needed but also providing consistent and meaningful diagnostic information to forum members and the community as a whole to help resolve any issues and get their sites up and running in a timely manner.

> This month Russ and the FPA team have worked on some of the outstanding issues and are on the verge of releasing a new and updated version, incorporating many new functions, features and sporting a new User Interface;
	•	Print to PDF, so you can pass the output to a 3rd party without leaving the script on your site,
	•	Simplified and less cluttered forum post generation workflow 
	•	Automatic checking and notification of  the FPA latest version.
	•	Automatic checking and notification of Joomla! latest release.
	•	FPA self destruct feature, auto-deleting 7 days after installation.
	•	Hosting Confidence Level indicating the probability of Joomla! successfully running on your server.
	•	New responsive user interface, including light and dark modes.
	•	Improved Accessibility and html validation
	•	Improved FPA report visual print styling.
	•	Many additional performance and security enhancements. 

> If you would like to try out the FPA and give it a run for its money—it's free, by the way—then go to ...

**Comment by mandville** [comment]
i can fluff it with these

and i am still grammar blocked with this sentence
t integrates into a post on the Joomla Forum, the FPA has become such an
integral


C Mandville
Joomla! Vulnerable Extensions List Team Leader
Joomla Security Strike Team Member
Joomla Trademark Team Leader
Unless indicated - this email discussion is not to be shared beyond the
original recipient

**Comment by RussW** [comment]
yeah, I know what you mean, I sort of "to'd and fro'd" with "integrate", which why I added the bit about being with a "post" as opposed to the "forum", maybe something like;

> producing a pre-composed report for use as a post on the Joomla Forum,

**Comment by sozzled** [comment]
I like that "... several well-known J! community members" :)

Russ' re-working is OK with me.

The word "integrate" means "to work with, assimilate", etc.; integration relates to incorporating a separate part into something else ... to make the something else "more whole".  Integral relates to structure, composition, constituency (as an adjective); integral relates to the whole "thing" being [constituently sound].  It's not a grammatical clumsiness; it's just that the words mean different things.  Integration and integral come from different Latin roots.

Aside from any lessons in English etymology, I don't really care.

**Comment by sozzled** [comment]
Here's the original sentence:
>Conceived by Russ Winter, to function as both a standalone tool and as a means of producing a report that integrates into a post on the Joomla Forum, the FPA has become such an integral part of the Joomla! world that it is used as the "go to" tool for anyone with website problems.

Here's how I would rework it
>Russ Winter conceived the FPA to function as both a standalone tool and as a means for generating a report on the Joomla Forum.  The FPA has become such an important part of the Joomla! world that it is used as the "go to" tool for anyone with website problems.

**Comment by RussW** [comment]
I'm happy with the last suggested changes, especially from a "readability" perspective changing the  "conceived" order flows better. Added the SSL Redirect to the list too, so it would now look like;

> Over a decade ago, a developer volunteering in the Joomla! Security Forum launched a suite of tools (Joomla Tools Suite) to help Joomlers diagnose issues with hosting, the installation and other matters associated with Joomla! Part of this suite was what is now known as the Forum Post Assistant or FPA.

> Russ Winter conceived the FPA, to function as both a standalone tool and as a means for generating a report on the Joomla Forum. The FPA has become such an important part of the Joomla! world that it is used as the "go to" tool for anyone with website problems. You can not only find out the state of your server, any possible conflicts that cause your site issues, but the tool also runs even if Joomla! isn't installed properly.

> Russ was then joined by several well-known Joomla! community members, Fiona Coulter, Claire Mandville and Phil DeGuy from the security forum team to further develop the tool, with the aid of "frostmakk", Michael Russell and "Webdongle" coding, testing and offering their help. 

> The combined talent, dedication and efforts of the FPA project team have helped untold numbers of Joomlers over the years, not only making it easier and simpler simpler for Joomla! beginners and veterans alike to get get help when needed but also providing consistent and meaningful diagnostic information to forum members and the community as a whole to help resolve any issues and get their sites up and running in a timely manner.

> This month Russ and the FPA team have worked on some of the outstanding issues and are on the verge of releasing a new and updated version, incorporating many new functions, features and sporting a new User Interface;
	•	Print to PDF, so you can pass the output to a 3rd party without leaving the script on your site,
	•	Simplified and less cluttered forum post generation workflow. 
	•	Automatic checking and notification of  the FPA latest version.
	•	Automatic checking and notification of Joomla! latest release.
	•	FPA self destruct feature, auto-deleting 7 days after installation.
	•	Automatic redirection to the https:// site, if a valid SSL certificate is found.
	•	Hosting Confidence Level indicating the probability of Joomla! successfully running on your server.
	•	New responsive user interface, including light and night modes.
	•	Improved Accessibility and html validation.
	•	Improved FPA report visual print styling.
	•	Many additional performance and security enhancements. 

> If you would like to try out the FPA and give it a run for its money—it's free, by the way—then go to ...

**Comment by mandville** [comment]
If there are no changes or ideas by saturday, i will upload to the magazine

**Comment by frostmakk** [comment]
You can use my real name.
We're not shady taggers.
😄

**Comment by mandville** [comment]
I didnt want to without permission due to gdpr. security reasons, seo reasons and because my dog said so.

**Comment by mandville** [comment]
Anyone want to do a couple of screenshots? i have pre dusty bin version

**Comment by RussW** [comment]
here's a bunch of images that they can choose from

![Screen Shot 2020-06-05 at 6 15 19 pm](https://user-images.githubusercontent.com/871931/83853762-16858b00-a759-11ea-8b24-ad9d6467cf4a.jpg)
 
 
![Screen Shot 2020-06-05 at 6 15 40 pm](https://user-images.githubusercontent.com/871931/83853782-1d140280-a759-11ea-8887-c3265e572b7a.jpg)
 
 
![Screen Shot 2020-06-05 at 6 16 16 pm](https://user-images.githubusercontent.com/871931/83853801-2309e380-a759-11ea-9e77-9e0403583df5.jpg)
 
 
![Screen Shot 2020-06-05 at 6 16 50 pm](https://user-images.githubusercontent.com/871931/83853823-2bfab500-a759-11ea-8852-c2a81c94ffc2.jpg)
 
 
![Screen Shot 2020-06-05 at 6 17 07 pm](https://user-images.githubusercontent.com/871931/83853838-3157ff80-a759-11ea-90ee-254bb891a41e.jpg)

**Comment by RussW** [comment]
and a night-mode image
 
 
![Screen Shot 2020-06-05 at 6 23 59 pm](https://user-images.githubusercontent.com/871931/83854288-d8d53200-a759-11ea-930b-3d9709ed7876.jpg)

**Comment by sozzled** [comment]
Thanks, @RussW 

I was just about to upload a few family photos when I saw that you'd already done them.  :+1:

**Comment by RussW** [comment]
Seeing as there was a deadline on this stuff for publication, hence a deadline on the actual release of the new version.... Maybe we need to make some choices;

**Release Name :** is currently "_**facelift**_" any other entertaining suggestions?

**Release Number:** seeing as this is really only a UI Rewrite, do we stay with the **v1.x.y**?
Personally, I think so, just skip to _**v1.6.0**_, otherwise are we going for the _**v2.0.0**_ theme as proposed a while back _(seeing as few functions have been updated, it doesn't feel like a v2 to me)_

@mandville would be nice to have a "**family** (team) photo of us all as well, but not sure how we would organise that...

If some one wants to put a small gird/collage together...

**Comment by RussW** [comment]
**VEL Live Check** is probably the last thing I would like to try and get in, before release & publication, but thats proving to be a little slow going at the moment from a GUI Integration perspective.

**Comment by sozzled** [comment]
It's a 2000-line rewrite.  I commented elsewhere, a few minutes ago, about dumping the v2.0 project (started in 2014 and updated again in 2017 but hasn't progressed) and using the "facelift" fork as the new FPA.

Maybe the cosmetics don't "feel" like a v2 to you but there's bucketload of eye-candy.  The repackaging of information (at least from the perspective of person who's using it) is a complete change from the iconic FPA 1.x of the past.  It's no different to, say, buying a plastic bottle of Coca Cola when all you've ever known was the traditional metal-capped glass bottle (kind of thing).

As far as codenames are concerned, I don't care:  we can run the ideas past @mandville's dog and see what the verdict is.

**Comment by RussW** [comment]
> It's a 2000-line rewrite. I commented elsewhere, a few minutes ago, about dumping the v2.0 project (started in 2014 and updated again in 2017 but hasn't progressed) and using the "facelift" fork as the new FPA.
> 
> Maybe the cosmetics don't "feel" like a v2 to you but there's bucketload of eye-candy. The repackaging of information (at least from the perspective of person who's using it) is a complete change from the iconic FPA 1.x of the past. It's no different to, say, buying a plastic bottle of Coca Cola when all you've ever known was the traditional metal-capped glass bottle (kind of thing).
> 
> As far as codenames are concerned, I don't care: we can run the ideas past @mandville's dog and see what the verdict is.

**So what are you saying about the version numbering?**

**Comment by sozzled** [comment]
My recommendation is that codename "facelift" should be released as v 2.0.0.   As long as @mandville's dog approves of the name.

Please look into https://github.com/ForumPostAssistant/FPA/issues/66

I'm a klutz with GitHub:  I'm not sure if I put things where they're supposed to go.  If I could use the bloody thing, if I know how to write a "PR", then I wouldn't have to describe in words when I see dodgy-looking PHP.

**Comment by mandville** [comment]
We dont have to release on the 15th. That's the article date. If it's a
notice of what's to come then that's fine.
 I'll read the rest of the email chain later.

**Comment by RussW** [comment]
ah ok, I guess I was thinking of working towards a release date and article date being the same thing, otherwise it seems a little pointless doing the article as the old "fugly" UI is all users will see. My mistake....

**Comment by mandville** [comment]
The article is to highlight the super new smashing new version .the cab
download the original or the branch..

**Comment by frostmakk** [comment]
Since we already have a 2.0 skeleton in the closet, I vote for 1.6.0
And facelift is as good as any release name.

**Comment by sozzled** [comment]
I vote to clear the deck and release as v2.0.0.

**Comment by mandville** [comment]
Naming wise i have a good idea for the next letter in the sequence 
rhytidectomy !

**Comment by mandville** [comment]
> 
> 
> **VEL Live Check** is probably the last thing I would like to try and get in, before release & publication, but thats proving to be a little slow going at the moment from a GUI Integration perspective.

i would hold off on com_vel integration.  reasons to become clear shortly

**Comment by sozzled** [comment]
@mandville I started a discussion about codenames at https://github.com/orgs/ForumPostAssistant/teams/development/discussions/2

(Nit-picking over the draft press release):  the comma in para 2 first sentence is unnecessary.  The first sentence of para 2 should read:

>Russ Winter conceived the FPA to function as both a standalone tool and as a means for generating a report on the Joomla Forum.

**Comment by sozzled** [comment]
I don't want to steal anyone's thunder but would anyone mind if I wrote a very short statement on the J! forum (in the FPA discussions) that outlined a few of the things we've been working on?

Something along the lines of:

>This month @RussW and the FPA team have been working on several outstanding issues and are near to releasing a new and updated version, with a new user interface incorporating many new functions, features, including:
>
>• Print to PDF, so you can pass the output to a 3rd party without leaving the script on your site,
>• Simplified and less cluttered forum post generation workflow.
>• Automatic checking and notification of the FPA latest version.
>• Automatic checking and notification of Joomla! latest release.
>• FPA self destruct feature, auto-deleting 7 days after installation.
>• Automatic redirection to the https:// site, if a valid SSL certificate is found.
>• Hosting Confidence Level indicating the probability of Joomla! successfully running on your server.
>• New responsive user interface, including light and night modes.
>• Improved Accessibility and html validation.
>• Improved FPA report visual print styling.
>• Additional performance and security enhancements. 

Would anyone object?

**Comment by mandville** [comment]
can this blurb be added to the magazine article and then released over the weekend jus in time for the magazine to tie it in?

**Comment by sozzled** [comment]
Sure (if you want to add something to the magazine article); no problem if you would like me to hold off on writing to the J! forum.  :sunglasses: 

Just wondering if we want to extend an invitation to other Joomlers or forum-dwellers to volunteer to join the team?

**Comment by mandville** [comment]
press release submitted to JCM/MJO

**Comment by frostmakk** [comment]
[https://magazine.joomla.org/all-issues/june-2020/a-facelift-for-the-forum-post-assistant](url)
