### ISSUE TITLE
Add database user privileges to postgres checks

### ISSUE THREAD

**Issue by RussW** [ForumPostAssistant/FPA#69]
The database user privs have been added to mysql, mysqli & mysqlPDO but not to postgres yet

**Comment by frostmakk** [comment]
@RussW 
PostgreSQL is quite a different beast than MySQL. There seems to be customizable privileges for every nut & bolt in the database. I'm struggling with picking out the few we need to determine if the user has sufficient privileges. 
There are two system tables we can query that could be used:
![image](https://user-images.githubusercontent.com/25645600/83970760-bec15e00-a8d7-11ea-8774-ce1a9ff75533.png)
or
![image](https://user-images.githubusercontent.com/25645600/83970775-d7ca0f00-a8d7-11ea-9600-4ffaa192c8ab.png)

Of course if the user is a super user, there is no need to look further, but what other roles/privileges/combinations in the tables do you think should be considered?

**Comment by RussW** [comment]
Yes, I had a quick look and saw that. Maybe once we get the current branch released, you and I can do some further research in to the postgres "roles" and "grants" and determine if we can do the same or similar as with mysql(i/PDO)

It looks like we need to query the users _role_ first, then find the _grants_ assigned to the role  after.

**Comment by frostmakk** [comment]
First attempt at presenting sufficient database-user privileges for PostgreSQL.
Check out branch PostgreSQL-User-Privileges.

**Comment by RussW** [comment]
apologies for the delay in responding @frostmakk, this is on my list to test in the next week or so, speak more then but looks great at the moment, great work

**Comment by frostmakk** [comment]
Included in v1.6.3
