### ISSUE TITLE
Versioning for the "2020-UI-Facelift branch/release

### ISSUE THREAD

**Issue by RussW** [ForumPostAssistant/FPA#71]
Appreciate there have been discussions elsewhere, but if we can make this reasonably short and painless; 

_To date the versioning options & preferences appear to have been the following:_

**v1.6.0** : @frostmakk , @RussW . @mandville 

**v2.0.0** : @sozzled 

_**Please add your preference...**_

**Comment by mandville** [comment]
is it  a few line fiddling - 1.6
is it a major code rewrite (including ui)  - 2.0.x

**Comment by sozzled** [comment]
There's nearly 2000 lines added from FPA v1.5.0 and there are many changes (not just the cosmetic UI ones) including most (if not all) of the ideas proposed for the original concept for v2.  So, I would say it's a major overhaul (even if many of the actual diagnostic checks haven't changed—and why would those things substantially change, anyway?)

It's still the FPA (of course) but it's a differently "flavoured"/looking FPA and, for that reason, let's not argue the toss.  Even though there may not be any B/C issues that I can tell (I haven't tested it with J! 1._x_ or J! 2.5 and I haven't any intention of doing that) it should work with all versions of J! right through to J! 4.  If this version doesn't work for someone who uses J! 1._x_ or J! 2.5 they can report to us (and use v1.5.0 as a fall-back).

Let's call it v2.0.0 to be on the safe side and be done with it.

Minor patches/fixes to this release would therefore be labelled v2.0.n.

My vote for the next version of the FPA (one that potentially includes connecting to the VEL) would be to label it v2.1.0.

**Comment by RussW** [comment]
There has been little to nothing done on the majority of the codebase, the test routines, data collection and post generation code, so it's a minor GUI update, still **v1.6.0** for me...

**Comment by sozzled** [comment]
Fair enough.  In this case, v2.0.0 will never eventuate because it's purely subjective as to whether a change in the code base (whether one adds/removes/changes one line or one thousand lines) warrants a "major" version relabelling.

We may as well close this issue now, IMO.

**Comment by RussW** [comment]
> Fair enough. In this case, v2.0.0 will never eventuate because it's purely subjective as to whether a change in the code base (whether one adds/removes/changes one line or one thousand lines) warrants a "major" version relabelling.
> 
> We may as well close this issue now, IMO.

@sozzled there are still two more people to have a definitive say (@mandville & @Webdongle ) whatever the majority vote is, is what will happen.

You may get your versioning choice, you may not, but _"spitting the dummy"_ isn't going to get us there any quicker or easier.

**Comment by sozzled** [comment]
Agreed.  :smile: I will accept the majority decision.

However, it's obvious to Jack Hill the blind miner that we're not going to obtain consensus on how much of a change is significant enough to create a v2.  Think about it:  v2 has been in the melting pot for over two years.  (Like the whingeing kids in the back seat saying, "Are we there yet?") :laughing:

**Comment by RussW** [comment]
My initial _v2.0.0_ proposal was a complete fpa re-write, GUI, test routines and BBCode output; hence my _personal assertion_ that this _is not_ now a _v2.0.0_ release. 

For me, although you are correct in saying a lot has changed, a good 95% or so of this update has purely been a GUI redesign and code cleanup, with a few new GUI based features, not the complete functional rewrite as originally proposed by me over 18 months ago (and hopefully I will now get around to archiving or deleting the orphan items of).  

but... as mentioned, time will tell, majority opinion will out...!

**Comment by mandville** [comment]
i am tempted to go for a 1.6 release based on Russ evidence

**Comment by RussW** [comment]
It's not as if we're "_playing for sheep stations_" and "_no ones going to die_" here folks, it's just a release/version number.

**Comment by RussW** [comment]
it a[ppears we have a winner - closed to v1.6.0
