### ISSUE TITLE
Proposal for ALL future release naming conventions

### ISSUE THREAD

**Issue by RussW** [ForumPostAssistant/FPA#72]
There's been a lot of discussion over the time about naming of pre~releases etc etc...

I'd like to suggest/propose that we assigned a single person to provide "names" as we go forward _(ignoring and overriding the current naming convention used in the 2020-UI-Facelift development, I just made that up to differentiate the branch from the older dev branches and have absolutely no care nor concern for it)_

**@mandville** _and your dog_, would you be willing to be the lead with this? Whatever you two come up with, for whatever reason, is the name of future releases and we simply use "_development_" as any interim name until the dog has approved the official name.

_Unless you desire, we don't have to stick to a theme or methodology, just an interesting name..._

**Comment by mandville** [comment]
i vote for names purely for the retro geek aspect, the dog would probably vote to drop the name, and if thats the case we can get arbitration from the guinea pigs or fish. 
naming so far has been next alphabet letter with a weird humorous  transliteration of the a suitable word
eg
kusala - balaned in budhism
 midden - irish for rubbish pile
 rhytidectomy - latin for facelift
working on basis that version x is a total faceliftr we could drop the naming

**Comment by sozzled** [comment]
Here is a list (in alphabetical order) of names:

Artemis
Balder
Cronos
Demeter
Enlil
Forseti
Gaia
Hermes
Iris
Janus
Kvasir
Loki
Morpheus
Nike
Odin
Phosphorus
Quetzalcoatl
Rhea
Saturn
Triton
Uzume
Vulcan
Wakahiru-me
Xippilli
Yamato
Zeus

[As I wrote in another place](https://github.com/orgs/ForumPostAssistant/teams/development/discussions/2), I feel that a name should be chosen when **_starting_** work on a change and not after completing that work.

**Comment by RussW** [comment]
Sorry @sozzled didn't see that list was elsewhere.

So the two current proposals are:

- **drop using names altogether**

- or are all happy to run with **rhytidectomy** (latin for facelift)

- other suggestion

For me (RussW), I'm happy with either, 1) or 2) makes no odds, go with the majority.

**Comment by sozzled** [comment]
I don't care if people use codenames (internally within the source code, during development, for a work-in-progress) or not.  I prefer that, when a product is released, the internal working name is not displayed.

FWIW, nearly all medical terms are based on Greek.  Rhytidectomy is Greek.

**Comment by RussW** [comment]
closed to "why does a whale..." and no other objections....
