### ISSUE TITLE
Change ordinal date format to cardinal days and abbreviated month format.

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#73]
The current FPA report displays the date as an ordinal number with the full month name

![fpaHeaderForum](https://user-images.githubusercontent.com/877778/83954779-84cc6980-a88f-11ea-83d3-32ce070bcc8b.jpg)

Most style guides for writers recommend the use of cardinal numbers in date formats.

Because different localities use different date representation formats (dd/mm/yyyy, mm/dd/yy, yyyy/mm/dd, etc.) a purely numerical representation of the month should be avoided.

I suggest the date format j-M-Y at line 4722 instead

In the illustrated example above, this would display as "2-Jun-2020".  Small saving in total character count; less likely to be misinterpreted by the reader.

**Comment by RussW** [comment]
will be done on the next minor commit

**Comment by RussW** [comment]
done at commit https://github.com/ForumPostAssistant/FPA/commit/c577f0e4d925c92a3aeead9ec6df6504aec83a8a

**Comment by sozzled** [comment]
Tested OK.  :+1:
