### ISSUE TITLE
Move important FPA version information to top

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#74]
Lines 207-209 contain

	define ( '_RES', 'Forum Post Assistant' );
	define ( '_RES_VERSION', '1.5.5 (rhytidectomy)' );
	define ( '_last_updated', '27-May-2020' );

Suggest a few things

1)  Move these (insert at) line 34
2)  Change the definition of _RES_VERSION to 
`	define ( '_RES_VERSION', '1.5.5' );`
3)  Create new definition of _RESas
`	define ( '_RES_CODENAME', 'rhytidectomy' );`
4) Modify the coding at line 3086 to display the codename if _FPA_DIAG is true
5) Modify the coding at line 3215 similarly
6) Ditto for line 4715

The other references to _RES_VERSION don't matter.

**Comment by sozzled** [comment]
Because I don't know how to build a PR, the attached file contains all the changes I mentioned earlier.  I had a couple of other ideas that I've incorporated; not too many changes, I hope.  To test, need to uncomment the line that defines _FPA_DEV.

[fpa-en.txt](https://github.com/ForumPostAssistant/FPA/files/4741260/fpa-en.txt)

This should make the file easier to maintain.

**Comment by RussW** [comment]
I'm ok with the way it works at the moment, see what everyone else thinks.

**Comment by sozzled** [comment]
I'm sorry I wasted an hour of my time.  I had hoped that the changes would (a) make life easier to maintain the file so that people wouldn't have to search and replace the version information in two places, (b) attend to the internal working name or "codename" matter so that the codename was only visible when testing during development, and (c) tidy things up a little.  

If you're happy with the way things work and others are happy with the way things work then I probably should remain "just a tester" and let you guys sort out how to fix things in future.

(Not really very happy)

**Comment by RussW** [comment]
**@sozzled  Mate..!  _"going off like a frog in a sock"_** serves absolutely no good purpose, especially considering others haven't shared their opinions/thoughts yet, it also being a Sunday or because I didn't review your changes for 8 hours because I was busy doing other stuff; not to mention that personally see no reason for such extensive changes _(with the exception of moving the versioning higher in the code for ease)_.

However, I do agree that it would be easier to update versioning if defined higher up in the code, which I will certainly do.

Splitting the resource version and name makes no odds, but for me, I kinda like displaying the name, it's gives a bit of character and interest.  

In saying that, if everyone agrees with hiding the name unless in dev mode then we'll do it.

_**everyone gets an opinion and say, hence the previous "vote style" issues**_

**Comment by sozzled** [comment]
I also fixed a regression error that you introduced in your last commit that I based my version on.  Your definition for deleted time was minus seven days.  I fixed that, too.

I'm not blaming you for taking time off on Sunday.  I'm just saying that it would be better to look at the differences between what I submitted and your own version and consider the merits of those two things before saying, in effect, that things are OK the way that you had them.

I hate the codename being displayed; I've always disliked it.  It serves no purpose to the end user and chews up the limited amount of forum post quota that people have.  Saving a dozen characters may not sound much but even a little bit may make the difference between being able to post the FPA report or having to split it.

I wish I could write PRs.

I wish we were able to have a group [voice] chat.  We could have this thing wrapped up in a day or two if we were able to share our opinions in real-time.  And, (sorry to be on a whinge) I don't like filling in time playing solitaire when I could actually be contributing something.

I just want you to understand how isolated I sometimes feel, that's all.  Anyway, let's wait until people have voted and I hope that commonsense prevails (not that I'm saying I have a monopoly on commonsense).

**Comment by sozzled** [comment]
I feel a little happier now.  Thanks for considering making a change or two.  Cheers.  I'm going out for dinner *woo-hoo*

**Comment by RussW** [comment]
bare-minimum, just moved the versioning and copyright info to just under the initial docblock, as discussed

**Comment by RussW** [comment]
closed as the original poster seems unconcerned
