### ISSUE TITLE
FPA (SELF_DESTRUCT) "Expiry Notification"

### ISSUE THREAD

**Issue by RussW** [ForumPostAssistant/FPA#75]
With the introduction of the _**SELF_DESTRUCT**_ feature, this raises the question of user confusion/surprise and additional forum questions about quite WTF happened...

In an effort to reduce this, the last commit offers an informational "_**Expiry Notification**_" under the menu navbar stating how many days are left before FPA expiry.

- **YES** this works...

- **NO** delete it, not necessary...

![Screen Shot 2020-06-07 at 7 19 13 pm](https://user-images.githubusercontent.com/871931/83965012-00600200-a8f4-11ea-8f99-8fcf2281a0aa.jpg)

**Comment by frostmakk** [comment]
Yes, this works. Maybe make the spoons even smaller?
"As a safety precaution, this copy of FPA will expire in x days, and will attempt to self-destruct if run later."

**Comment by sozzled** [comment]
Disagree with suggested implementation.  Therefore, will abstain from voting.

**Comment by RussW** [comment]
The proposed _"Expiry Notification"_ has been moved to just under the Joomla & FPA checking output, with an enhanced message (as above). 

_**However...**_ due to the changes made for "localhost" development environments now not deleting the FPA, it is no-longer needed to be displayed on localhost environments.
