### ISSUE TITLE
"LAST PHP ERRORS REPORTED" should come from the current site only

### ISSUE THREAD

**Issue by toivo** [ForumPostAssistant/FPA#76]
When tested in Wampserver 3.2.2 with several virtual hosts, the last PHP error is reported from the PHP error log even if the website is hosted in a different virtual host.

In the attached example the FPA results from a Joomla 3.9.19 site show a PHP error from a Joomla 4 beta site.

![fpa-155-php-error](https://user-images.githubusercontent.com/1175079/83970948-1d53ff80-a90b-11ea-8bf3-cd796f28ea0a.jpg)

**Comment by frostmakk** [comment]
That's probably more of a Wamp issue than FPA.
AFAIK there's only one php-errorlog for each php-version, not for each virtual host.

**Comment by RussW** [comment]
As far as I am aware, @frostmakk is correct and "_Production Servers_" configure the virtual hosts to logout to their own unique log folders & files within their own home/ directory, whereas localhost development environments tend not to configure that functionality, so FPA can only look at the joint/common log files.

**Comment by toivo** [comment]
Fair enough, no problem.
