### ISSUE TITLE
Consistent use of _RES vs. _FPA constants

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#80]
There are many places in the source code that define constant names as _RES_XXXXXX
There are equally many places in the source that define constant names as _FPA_XXXXXX

In effect they are the same thing (unless there is a constant named, for example, _RES_FRED and _FPA_FRED, that would cause a run-time error or logic bomb if renamed the same).

Whether or not this single script is "standalone", a "package" in its own right, or part of a bigger package, I suggest renaming all locally-defined constants consistently to aid with future maintainability ... for those who come after us.

Suggest renaming all constants currently named as _RES_XXXXXX as _FPA_XXXXXX or, altenatively, rename all  _FPA_XXXXXX constants as _RES_XXXXXX or (third neutral choice) rename all _RES and _FPA constants as _PKG.

**Comment by mandville** [comment]
i have no objections
