### ISSUE TITLE
Who uses tarball?

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#82]
Lines 288-290

    define ( '_RES_FPALINK', 'https://github.com/ForumPostAssistant/FPA/tarball/en-GB/' ); // where to get the latest 'Final Releases'
    // @RussW updated 23/05/2020
    define ( '_RES_FPALATEST', 'Download the latest FPA release (tar.gz)' );

Fair enough but most people download the zip.  Tarballs have some niche market value but the average Joe usually wouldn't know what to do with one; they're not natively understood in Windows unless you have an extraction tool such as _WinRAR_.

**Comment by RussW** [comment]
although .zip is the most popular, a large number of unix users do not use .zip as it is not the native format, no reason not to offer it seeing as it's there on Github with no extra effort.

**Comment by sozzled** [comment]
As long as both options are available, with  .zip format as the first preference, I would be OK with that.   Yes?

**Comment by RussW** [comment]
Is this done?

**Comment by sozzled** [comment]
I can't tell (when I execute the script) if this is done or not.

When you click the "download" button, two other options appear but neither are navigable on my browser.  The button, itself, targets FPA v1.5.0.  Looks like the .zip file is what's downloaded.

![fpaDownloadLinks](https://user-images.githubusercontent.com/877778/84215556-fdd6f580-ab09-11ea-88b8-9e502850bee7.jpg)

**Comment by RussW** [comment]
There is no link in the popover, and the main button links only to the .zip file. I can click on it and download from Mac Safari, Opera, Firefox and Chrome. Which browser are you using (assuming you're on on Windows)?

**Comment by sozzled** [comment]
Ahhh, OK.  Thanks for the explanation.  The pop-up is an informational display and not meant to be clicked.  Suggest (as a possible improvement) wording like this:

ℹ Click to download the latest FPA script (.zip) format assumed.

or

ℹ Click to download the latest FPA script (.tar.gz) format assumed.

As the case may be.  Would this be better?

**Comment by sozzled** [comment]
On second thoughts, maybe not.  I don't want to add unnecessary extra work.  The other popups would be out of step.  Forget most of what I wrote.  I understand, now, the purpose of the popup.  It's not meant to be clicked.

I think it's all done.  I'll close this and we can move along.  Thanks.

**Comment by sozzled** [comment]
@RussW wrote:
>Which browser are you using (assuming you're on on Windows)?

Most of the time I use _Mozilla Firefox_.  .zip is presented when I use _Google Chrome_, _Opera_, _Internet Exploder_, _Safari for Windows_ (doesn't work properly, anyway), _MS Edge_ in all cases.  I prefer to work with _Mozilla Firefox_ because I'm comfortable with the "inspector tools".

Not much point in in me testing any download feature with _Safari_ on an iPhone or iPad because there's nowhere to download to.
