### ISSUE TITLE
Consistent use of (abbreviated) number forms

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#83]
The source contains references to "KiB" , "MiB" and "GiB".  These abbreviations are not in common/conventional use.

Recommend changing all "KiB" to "KB", "MiB" to "MB" and "GiB" to "GB"

**Comment by RussW** [comment]
We calculate using 1024 (not 1000), hence the the use of standard KiB, MiB & GiB designations.

**Comment by mandville** [comment]
old school - 1024 - i understand rounding things up but thats just being lazy

**Comment by RussW** [comment]
It's the difference between techie math and salespersons math.

As far as I am aware _(and remember)_ it's always been 1024, and the textual designations were updated many revisions ago to reflect that.  I honestly don't see the problem with them as they are and personally use the 1024 calculation.

**Comment by sozzled** [comment]
@RussW is technically correct.  That's not what I was taught at university but the nomenclature was changed 20 years ago and KiB is technically more accurate than KB, if we're dividing by 1000 and not by 1024.

**Comment by RussW** [comment]
Is this done now folks?

**Comment by sozzled** [comment]
The last time I looked it all seems OK.  I'll close this issue.
