### ISSUE TITLE
Change "SEF URL'S" to "SEO SETTINGS" and related matters

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#84]
For consistency with J!'s **Global Configuration** panel, change the following lines in the FPA

Line 4838, from

                                                echo '[b]'. _FPA_CFG .' '. _FPA_OPTS .' :: Offline:[/b] '. $instance['configOFFLINE'] .' | [b]SEF:[/b] '. $instance['configSEF'] .' | [b]SEF Suffix:[/b] '. $instance['configSEFSUFFIX'] .' | [b]SEF ReWrite:[/b] '. $instance['configSEFRWRITE'] .' | ';
                                                echo '[b].htaccess/web.config:[/b] ';

to

                                                echo '[b]'. _FPA_CFG .' '. _FPA_OPTS .' :: Offline:[/b] '. $instance['configOFFLINE'] .' | [b]SEO:[/b] '. $instance['configSEF'] .' | [b]SEF Suffix:[/b] '. $instance['configSEFSUFFIX'] .' | [b]SEF ReWrite:[/b] '. $instance['configSEFRWRITE'] .' | ';
                                                echo '[b].htaccess/web.config:[/b] ';

Line 5825, from

                                                        <div class="d-block xsmall bg-light text-uppercase text-dark py-1 mb-1">SEF URL's</div>

to

                                                        <div class="d-block xsmall bg-light text-uppercase text-dark py-1 mb-1">SEO SETTINGS</div>

Fix typo at line 174, from

     * - if $isLOCAL = 1 : don't even access the _FPA_SEF_DESTRUCT routine

to

     * - if $isLOCAL = 1 : don't even access the _FPA_SELF_DESTRUCT routine

**Comment by RussW** [comment]
As the output(s) are explicitly displaying SEF settings, although the section heading is SEO, I'd be suggesting leaving the FPA option names as they are, so they directly relate to the displayed item.

Other changes done

**Comment by sozzled** [comment]
What's internal (to the program) is internal to the program.  What's displayed to the user should reflect the user's common understanding.  SEF URL's is just plain wrong (grammatically and semantically) when there's no such "setting" in J!.

Leave the variable names the same but I recommend changing what's displayed on the screen and in the FPA BBcode.

**Comment by RussW** [comment]
![Screen Shot 2020-06-09 at 9 36 11 am](https://user-images.githubusercontent.com/871931/84090360-e8dc6280-aa34-11ea-8c01-72322e29f71f.jpg)
![Screen Shot 2020-06-09 at 9 34 55 am](https://user-images.githubusercontent.com/871931/84090361-ea0d8f80-aa34-11ea-900f-6c93768fc73b.jpg)

**Comment by sozzled** [comment]
That's one of three settings under the Heading "SEO Settings" in J!'s **Global Configuration**.  I would like to keep these things the same

![fpaSEO-settings](https://user-images.githubusercontent.com/877778/84090648-ba12bc00-aa35-11ea-9575-fe09200afbf3.png)

Yes, there's a "Search Engine Friendly URLs" setting within that group.  I'm talking about what the user sees on their screen and what is displayed in the FPA BBcode, that's all.  OK?

**Comment by RussW** [comment]
yes, and the "actual" items being displayed are the **SEF settings**

**Comment by sozzled** [comment]
Where do you see "SEF Settings" in the **Global Configuration**?  I only see "SEO Settings" (with five separately configurable items under that heading).  I think it's better to use the Global Configuration heading for what's displayed in the FPA and leave the actual items as they are.

**Comment by RussW** [comment]
Each setting being displayed **is** directly related to **SEF** only, not _SEO_ as a whole, hence the panel heading being **SEF* not _SEO_

**Comment by sozzled** [comment]
I disagree but I'll quietly acquiesce.  I think my suggestion would be more relevant to the end user (to help them find what they may need to inspect or change) and you're taking a harder line, but _c'est la vie_.  When it comes to usability our first priority should attend to the end user's experience.

**Comment by RussW** [comment]
It's a personal opinion impasse, I feel the same way regarding the changes, users have always discussed the SEF URLs, not SEO, hence I feel usability would be reduced with that change.

**Comment by sozzled** [comment]
OK.  I'll close the discussion now.  It can be revisited if/when anyone asks about what "SEF Settings" means and why it's used in the FPA but people need to look 
(a) in J! 3.x, **System** » **Global Configuration** » **Site** (to find **SEO Settings**) to change one or more of those SEF-related things, or
(b) in J!4, **System** » **Setup** » **Global Configuration** » **Site** (to find **SEO**, after you scroll down a-ways) to change those things.
