### ISSUE TITLE
To do:  create LICENSE.md

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#85]
Not sure how to do this.  I looked around at other LICENSE.md files with other J! projects and it seems that everyone just quotes the GNU GPL.

[GNU GPL.txt](https://github.com/ForumPostAssistant/FPA/files/4749284/GNU.GPL.txt)

**Comment by RussW** [comment]
Is this done now? 
The LICENSE.txt in the documentation folder was updated to the latest GNU GPL v2, with their new address and other updates regarding libraries etc.

**Comment by sozzled** [comment]
I haven't done anything more than offer a suggestion (to create a new file in the repo) as I did in the opening post in this discussion.  I don't know how to add/change files in the repo.

**Comment by RussW** [comment]
As mentioned, the current location (Documentation/" where we hold the Licensing Information has been updated, as per your file/request. Not sure we have a need to put it in the "/" folder as well.

**Comment by sozzled** [comment]
OK.  I won't flog this:  normally the licensing stuff would be located in the root folder (that's where I would expect to find it) just like the README (unless there's a separate README for the doco.)  It's probably a case of personal preference:  I might do it differently to you and _vice-versa_.  Others can offer their views for one place or the other.  Thanks.

**Comment by RussW** [comment]
https://github.com/ForumPostAssistant/FPA/commit/cebdd75b5bb1b20ae779adc62c1b3b461b56859a

**Comment by sozzled** [comment]
Thanks. (LICENSE or LICENSE.md)?

**Comment by sozzled** [comment]
Sorry for re-opening the issue.  Please look at LICENSE (or LICENSE.md or whatever it's called).  _cf_ picture below:

![fpaUseGPL3 0](https://user-images.githubusercontent.com/877778/84237185-3db6d080-ab3c-11ea-968c-1563f6acd13e.jpg)

**Comment by RussW** [comment]
nope, decided to stay inline with Joomla! license at GNU GPL 2, June 1991

**Comment by sozzled** [comment]
The source code refers to GPL v3.  I thought you may want to keep everything in step?

**Comment by RussW** [comment]
we will, in **due course**... _**these things take time** (you could always provide a PR to assist with maintenance)_

everything will be GNU GPL 2, June 1991

**Comment by sozzled** [comment]
If I knew **_how_** to write a PR I would provide you with a PR.  I don't know how to do that.

**Comment by RussW** [comment]
https://opensource.com/article/19/7/create-pull-request-github

**Comment by sozzled** [comment]
When I have a month of Sundays to read that then we'll see what I can do.  Sorry but I just don't have the time to learn this yet.

**Comment by RussW** [comment]
We will look forward to your future Github knowledge development and continued support and contributions... Until then we will have to muddle along without your PR's or commit's...

**Comment by sozzled** [comment]
Huh?  I'm not sure I understand what you mean by "we will have to muddle along without" my help (in whatever form it takes).  Is that what you mean?

I can only contribute what I can contribute.  Do you mean that I have to learn Git before I may be useful?  :disappointed:
