### ISSUE TITLE
Privacy radio buttons

### ISSUE THREAD

**Issue by frostmakk** [ForumPostAssistant/FPA#87]
There is something odd going on with the privacy radio buttons.
When the script is run it opens with privacy off as expected. When you hit the generate post button they flip and the GUI changes to privacy on.

**Comment by RussW** [comment]
I think I've got it worked out, my mistake for got to change the original radios (in the options panel) to the new "0" (off) or "1" (on) from the old "1" (none)  & "2" (partial) 

eg: "1" was used at crossed-purposes New 1 = on, old 1 = none;
https://github.com/ForumPostAssistant/FPA/commit/caba3c487c63fc22a4325662f786505fd696e0f1

**Comment by sozzled** [comment]
This seems to work (for me anyway).  Thanks.

**Comment by frostmakk** [comment]
Looking good now.
Closing issue.
