### ISSUE TITLE
ForumPostAssistent / docs

### ISSUE THREAD

**Issue by frostmakk** [ForumPostAssistant/FPA#90]
Upon release of rhytidectomy, docs should be updated.
In the quick start guide at least this step will be outdated.
![image](https://user-images.githubusercontent.com/25645600/84206070-b66f4b80-aaae-11ea-9bc5-be1542391090.png)

The administrator guide is only half written.
Any takers?

**Comment by sozzled** [comment]
At the same time as you wrote this, @frostmakk, I had the same thoughts, too.

**Comment by RussW** [comment]
My thoughts were to do a minor "framework rewrite to make it simpler and move away from using the standard "jekyll" and just making it html pages (there will be no dynamic options as we can't use PHP on Github pages, and moving away from jekyll removes embedding any Github dynmaic functions, but I don't see that as a big problem as at the moment I think the only dynamic thing is automatically pulling the latest versioning

**Comment by frostmakk** [comment]
As sozzled mentioned in the duplicate issue, most of the content in the documentation folder is obsolete, and can be trashed. There is however one thing I wold like to be carried over to the online docs. A step 8 with something like:  
* If the FPA has picked up a PHP error message, you may want to check if there is something in the message you want to mask. Edit directly in the post if needed, and preview again. Submit the post to the forum when satisfied.

Now. We have mentioned it. Our hands are clean. 😎

**Comment by mandville** [comment]
>     * If the FPA has picked up a PHP error message, you may want to check if there is something in the message you want to mask. Edit directly in the post if needed, and preview again. Submit the post to the forum when satisfied.


suggest
The PHP error message may contain confidential information, please review and edit as needed before posting.

**Comment by RussW** [comment]
I'm certainly happy with just removing the "Documentation/" folder, I was going to ask if still wanted the images anyway.

I will take on converting the jekyll docs site to straight html and updating, once we have released and potentially any currently unnoticed omissions/errors are reported.

And then if there is a desire for a PDF User Guide, it can be generated in-part from the docs site to reduce a little extra work and overhead, including adding new notes etc.

**Comment by RussW** [comment]
**GNU GPL v2**    **NOT v3**

**Comment by sozzled** [comment]
@RussW:  I think I've done as you asked,

**Comment by sozzled** [comment]
My first PR! :flushed: :cold_sweat:

**Comment by RussW** [comment]
Can we close this to "Documentation Update Issue : https://github.com/ForumPostAssistant/docs/issues/6 ?

**Comment by frostmakk** [comment]
Yes. Looks like everything here has been taken care of.
Closing.
