### ISSUE TITLE
Update documentation instructions

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#91]
If accepted as the new main branch, the overhaul of the GUI makes the existing documentation included as a .pdf file obsolete:  the screenshots in the .pdf don't marry with the user's experience.

Although I'm a solitary voice in recommending that the new version (containing about 2000 lines of additional code) should be released as v2, the overhaul means that someone probably should revisit the .pdf, replace the screenshots, and include a new document with the FPA package.

From what I can tell, the [existing documentation](https://github.com/ForumPostAssistant/docs) (albeit much of it still a work-in-progress) is good enough as a quick start guide.  It contains enough information to get people going.

Questions: 
1)  Do we need a .pdf?  (Might be useful if someone doesn't have access to the internet, I suppose.)
2)  Who wants to volunteer themselves to revisit the .pdf?
3)  Not a show-stopper but it may raise questions on the J! forum, perhaps?

**Comment by sozzled** [comment]
Can someone please merge this issue with the same matter raised a few moments ago by @frostmakk (https://github.com/ForumPostAssistant/FPA/issues/90).

**Comment by frostmakk** [comment]
Just copy what you wrote and paste as comment in the other issue, and close this.
Don't believe merging is an option in here.
