### ISSUE TITLE
Can I (we) cleanup some of the old v2 issues/project/branches?

### ISSUE THREAD

**Issue by RussW** [ForumPostAssistant/FPA#92]
Just some housekeeping, is it time to delete/close or where possible archive the project, branches and issues referencing *v2* ?

**Comment by sozzled** [comment]
I think you know my views on the subject. :wink:

**Comment by frostmakk** [comment]
I can only find the FPA_2.0_Development branch, and the FPA Rewrite issue.
It doesn't look like any real work was done in this branch, so could probably just be deleted.
FPA Rewrite issue can be closed.

**Comment by RussW** [comment]
AWESOME! I'll do some housekeeping this evening, thank you

**Comment by RussW** [comment]
probably all done - closing unless I've missed anything

**Comment by sozzled** [comment]
Question:  A while back you asked about removing the translation branches.  (I can't find where you wrote that right now but I'm sure you'll find it easier to locate where.)

**_I_** have no objection to doing that.
