### ISSUE TITLE
Missing DB collation / character set v1.6.0

### ISSUE THREAD

**Issue by sozzled** [ForumPostAssistant/FPA#95]
I don't know if there's a regression error here but I can't find where the BBcode report displays the DB collation / character set.  Has this feature been dropped intentionally or by accident?

**Comment by frostmakk** [comment]
Intentionally, a couple of versions ago.

**Comment by sozzled** [comment]
Thank you, @frostmakk.  There must have been a good reason for removing this.

Does this mean that the information contained in the desktop view is incorrect?  Do you remember the reason that this facility was removed from the FPA around the time of v1.5.0?  It's not a complaint, I'm just wondering why.  The DB collation/character set information could be useful (if the information is reliable) in diagnosing some J! website user problems.  Yes / no?

**Comment by frostmakk** [comment]
No.
Joomla creates the collations / character sets it need per table.
The default database collation / character set is useless information.

**Comment by sozzled** [comment]
Thanks.  Makes sense to me, too!  :+1: 

Does that mean that the information (see following screenshot) is [kind of] meaningless, too?

![fpaDBcharset](https://user-images.githubusercontent.com/877778/84424793-f0ce1980-ac63-11ea-9d53-a5a3388bd07b.jpg)

It's not a problem.  I'm just getting a better understanding of the kinds of questions that people may ask.  :sunglasses:   We'll probably close this discussion soon.
